package com.example.dd.ilgitur;


import android.content.Intent;
import android.support.v4.app.NavUtils;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.MenuItem;
import android.view.View;


import android.widget.AdapterView;
import android.widget.ExpandableListView;
import android.widget.ExpandableListView.OnChildClickListener;
import android.widget.TextView;

public class rehber extends AppCompatActivity {
    ExpandableListView rehberler;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_rehber);

        getSupportActionBar().setDisplayHomeAsUpEnabled(true);


        rehberler = (ExpandableListView) findViewById(R.id.rehberListe);
        rehberler.setAdapter(new Islemler(this));


        rehberler.setOnChildClickListener(new OnChildClickListener() {
            @Override
            public boolean onChildClick(ExpandableListView expandableListView, View view, int i, int i1, long l) {
                Intent in = new Intent(getApplicationContext(), RehberIcerik.class);

                String b;

                String baslik=((TextView)view).getText().toString();

                if (((TextView) view).getText().toString() == "TAVAF DUALARI") {
                    in.putExtra("baslik",baslik);
                    b = "Tavaflarda herkes istediği duayı yapabilir; bunun için özel bir dua bulunmamaktadır. Bununla birlikte ulemanın tesbit ettiği dualar vardır. Ancak, Peygamberimiz her şavtta, Rükn-ü Yemenî denilen ve Kabe’nin güneyine düşen Yemen köşeşinden itibaren Hacer-ül Esved’e kadar, Rabbena Atina duasını okumuştur.\n" +
                            "Tavaf’ın 1. Şavtında Okunacak Dua:\n" +
                            "Şanı yüce olan, her türlü noksanlıktan uzak bulunan Allah’ı tesbih ederim. Her türlü hamd Allah’a mahsustur. Allah’tan başka ilah yoktur ve Allah en büyüktür. Azamet sahibi Allah’tan başka güç ve kuvvet sahibi yoktur. Allah’ın da salat ve selam ettiği Allah’ın Rasulü Muhammed’in üzerine salat ve selam olsun. Ey Allah’ım! Sana, iman ederek, Kitabını tasdik ederek, ahdini tutarak, senin Nebi’n ve sevgilin olan Muhammed’e (s.a.v.) uyarak geldim. Ey Allah’ım, ben, afv ve afiyetler istiyorum, dinde olsun, dünya ve ahirette olsun daimi afiyetler istiyorum. Cennetine kavuşmak ve Cehenneminden kurtulmak istiyorum. (Bana bunları nasib eyle ya Rabbi.)\n" +
                            "Rükn-ü Yemani’ye Gelince:\n" +
                            "Ey Rabbimiz! Dünyada da ahirette de bize iyilikleri ver. Ey Aziz, ey bağışlaması bol olan Alemlerin Rabbi! Cehennem ateşinden bizi koru. İyilerle birlikte bizi Cennetine girdir.\n" +
                            "Ancak, her ne kadar insanlar, öpmek için birbiri ile mücadele etse de Kabe’nin duvarları öpülmez. Üstelik, burada itişip-kakışmak ihram yasaklarına girmektedir. Gerekli olmayan bir hareketi yapmak yerine, yasaklara bulaşmaktan uzak kalmak elbette ki daha hayırlıdır. Bu konuya çok dikkat etmelidir. Hacer-ül Esved’in yanına gelince de Hacer-ül Esved tekrar selamlanır ve 2. şavta başlanır.\n" +
                            "Tavaf’ın 2. Şavtında Okunacak Dua:\n" +
                            "Ey Allah’ım! Bu ev, senin evindir. Bu Harem, senin haremindir. Güvenlik ise sadece senden gelen güvenliktir. Kul, senin kulundur. Ben de senin kulunum. Senin kulunun çocuğuyum. Burası, cehennemden sana sığınanların yeridir. Ey Allahım! Bize imanı sevdir, onu kalbimize süsle. Bizi, küfürden, fısıktan ve isyandan tiksindir. Bizi doğruya erenlerden eyle. Ey Allahım! Bizi, kullarını yeniden dirilteceğin günün azabından koru. Cennetine hesabsız girenlerden eyle.\n" +
                            "Rükn-ü Yemani’ye Gelince:\n" +
                            "Ey Rabbimiz! Dünyada da ahirette de bize iyilikleri ver. Ey Aziz, ey bağışlaması bol olan Alemlerin Rabbi! Cehennem ateşinden bizi koru. İyilerle birlikte bizi Cennetine girdir.\n" +
                            "Tavaf’ın 3. Şavtında Okunacak Dua:\n" +
                            "Ey Allah’ım! Ben, şekten, şirkten, ayrılıktan, iki yüzlülükten, kötü ahlaktan, kötü görünüşten, malıma, aileme ve evlatlarıma çirkin bir dönüşten sana sığınırım. Ey Allah’ım! Hiç şüphesiz senin rızanı, Cennetini istiyorum. Senin gazabından ve Cehenneminden yine sana sığınırım. Ey Allah’ım! Kabir fitnesinden de sana sığınırım, ölümün ve hayatın fitnesinden de sana sığınırım.\n" +
                            "Rükn-ü Yemani’ye Gelince:\n" +
                            "Ey Rabbimiz! Dünyada da ahirette de bize iyilikleri ver. Ey Aziz, ey bağışlaması bol olan Alemlerin Rabbi! Cehennem ateşinden bizi koru. İyilerle birlikte bizi Cennetine kabul et.\n" +
                            "Tavaf’ın 4. Şavtında Okunacak Dua:\n" +
                            "Ey Allah’ım bunu kabul edilmiş bir Hac (veya Umre) kıl. Çalışmalarımı şükretmeye değer çalışmalardan, günahlarımı affedilmiş günahlardan, amellerimi de salih ve makbul amellerden eyle. Ey Kalplerde olanları bilen Allah’ım! Beni karanlıklardan aydınlığa çıkar. Ey Allah’ım! Ben senin rahmetini kazandıracak şeyleri, mağfiretini kazandıracak çalışmaları, her türlü günahlardan, kötülüklerden kurtuluşu, her türlü iyilikte zenginliği, cennete kavuşmayı, ama, cehennemden kurtulmayı istiyorum. Beni rızıklandırdığın şeylere kanaat etmeyi, bunlardan bana verdiklerini bereketli kılmanı, benim bilmediğim, ama, senin bildiğin iyilikleri de bana ver.\n" +
                            "Rükn-ü Yemani’ye Gelince:\n" +
                            "Ey Rabbimiz! Dünyada da ahirette de bize iyilikleri ver. Ey Aziz, ey bağışlaması bol olan Alemlerin Rabbi! Cehennem ateşinden bizi koru. İyilerle birlikte bizi Cennetine kabul et.\n" +
                            "Tavaf’ın 5. Şavtında Okunacak Dua:\n" +
                            "Ey Allah’ım! Beni, senin gölgenden başka hiçbir gölgenin olmadığı ve senden başka hiçbir şeyin baki olmadığı günde, senin arşının gölgesinde gölgelendir. Beni, peygamberin olan Muhammed’in (s.a.v.) havuzundan bir daha hiç susamayacak şekilde sula. Ey Allah’ım! Ben, senden, senin peygamberin Muhammed (s.a.v.), hangi hayırları istemişse onları istiyorum. Ve, senin peygamberin Muhammed (s.a.v.), hangi şeyden sana sığınmış ise onlardan ben de sana sığınıyorum. Ey Allah’ım! Ben, senden cenneti istiyorum. Cennet nimetlerini istiyorum. Cennete yaklaştıracak, söz, fiil veya amelleri diliyorum.\n" +
                            "Rükn-ü Yemani’ye Gelince:\n" +
                            "Ey Rabbimiz! Dünyada da ahirette de bize iyilikleri ver. Ey Aziz, ey bağışlaması bol olan Alemlerin Rabbi! Cehennem ateşinden bizi koru. İyilerle birlikte bizi Cennetine kabul et.\n" +
                            "Tavaf’ın 6. Şavtında Okunacak Dua:\n" +
                            "Ey Allah’ım! Biliyorum, senin benim üzerimde pek çok hakkın bulunuyor. Yine senin yarattıklarınla benim aramda da haklar var. Ey Allah’ım, senin, benim üzerimde olan haklarını affeyle. Yarattıklarına ait olanların yükünü üzerimden kaldır. Helal olan nimetlerinle bana bolluk ver ve haramından sakındır. Ey mağfireti bol olan Allah’ım! Sana itaat edip, sana isyan etmekten, senin lütfuna kavuşup, senden başkasına muhtaç olmaktan beni kurtar. Ey Allah’ım! Şu evin gerçekten de çok azametlidir. Sen de çok şereflisin. Ve sen ey Allah! Halim’sin, Kerim’sin, Azim’sin. Beni affeyle, çünkü sen, affetmeyi seversin.\n" +
                            "Rükn-ü Yemani’ye Gelince:\n" +
                            "Ey Rabbimiz! Dünyada da ahirette de bize iyilikleri ver. Ey Aziz, ey bağışlaması bol olan Alemlerin Rabbi! Cehennem ateşinden bizi koru. İyilerle birlikte bizi Cennetine kabul et.\n" +
                            "Tavaf’ın 7. Şavtında Okunacak Dua:\n" +
                            "Ey Allah’ım, ben senden kamil bir iman, sadık bir bilgi, geniş bir rızık, huşulu, titreyen, ürperen, korkan bir kalp, zakir bir dil, temiz ve helal kazanç, samimi bir tevbe, ve ölümden önce tevbe istiyorum. Ölüm anında kolaylık, ölümden sonra mağfiret ve rahmet ile hesap anında af, Cennetine varmak ve Cehennemden kurtulmak istiyorum. Çünkü senin rahmetin çok geniştir, ey aziz ve çok bağışlayıcı olan Allah’ım. Rabbim, benim ilmimi artır ve beni salihlerden eyle.\n" +
                            "Böylece 7. şavtın bitiminde Tavaf tamamlanmış olur. Tavafın sonunda Hacer-ül Esved tekrar selamlanır. Daha sonra iki rekat tavaf namazı kılınır. Tavaf Namazı mümkün ise, Makam-ı İbrahim’i ön tarafa alarak kılınır. Eğer kalabalık dolayısıyla bu mümkün değil ise Mescid’in içinde Kabe’ye yakın bir yerde kılınır. Tavaf Namazının, birinci rekatında Kafirun Suresi, ikinci rekatında da İhlas Suresi okunur. Namaz kılmanın kerahet olduğu zamanlarda bu namaz da kılınmaz; kerahet vakti geçince kılınır. Tavaf namazından sonra müsait bir yerde Zemzem içmeye gidilir. Zemzem kuyusundan içmek şart değildir. Zemzemi Kabe’ye dönük olarak içmek daha uygundur. Zemzem içildikten sonra da Kabe’ye dönülerek şu dua yapılır:\n" +
                            "Ey Allah’ım, ben senden, faydalı bir ilim, geniş bir rızık ve her türlü dert ve sıkıntıdan kurtulmayı istiyorum. Ey şereflilerin ve ikram edenlerin en önde geleni olan Allah’ım! Beni, lutfunla ve kereminle, peygamberin olan efendimiz Muhammed’in (s.a.v.) havuzundan sula.\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "SAY DUALARI") {
                    in.putExtra("baslik",baslik);
                    in.putExtra("rehber", "Sa’y’ın 1. Şavtında Okunacak Dua:\n" +
                            "Allah en büyüktür, Allah en büyüktür, Allah en büyüktür, Allah büyüklerin en büyüğüdür. Allah’a binlerce şükürler olsun, çünkü her türlü hamd ona yapılır. Her şeyden münezzeh olan Allah, azamet sahibidir. O’na gece gündüz, sonsuz hamd ederiz. Azamet sahibi Allah’tan başka güç ve kuvvet sahibi yoktur. Tek\n" +
                            "olan Allah’ın kendisinden başka hiçbir ilah yoktur. O’nun ortağı da yoktur. Mülk ve iktidar O’nundur. Hamd O’nundur. O, diriltir ve öldürür. O kendisi, diridir ve hiç ölmez. Hayır da O’nun elindedir. O her şeye hakkıyla gücü yetendir. Ve dönüş de O’na olacaktır.\n" +
                            "Sa’y’in 2. Şavtında Okunacak Dua:\n" +
                            "Allah en büyüktür, Allah en büyüktür, Allah en büyüktür. Hamd sadece Allah’adır. Allah’dan başka hiçbir ilah yoktur. O Allah ki, yalnızca bir tekdir ve her şey kendisine muhtaçtır. Ve O Allah’ın, ne yoldaşı ne de çocuğu vardır. O’nun mülkünde ve iktidarında ortak olamaz ve olmaz. İşlerini yapması için de bir yardımcıya ihtiyacı da olmaz. Öyleyse, O Allah’ı en büyük bil ve öyle inan. Ey Allah’ım! Sen şüphesiz indirdiğin kitabında şöyle diyorsun: Bana dua edin, yalvarın, size hemen cevap verip karşılığını bahşedeyim. Rabbimiz, bize emrettiğin gibi sana gelip yalvarıyoruz: Bizi affeyle! Çünkü sen hiçbir zaman vaadine muhalefet etmezsin!\n" +
                            "Sa’y’in 3. Şavtında Okunacak Dua:\n" +
                            "Allah en büyüktür, Allah en büyüktür. Allah en büyüktür. Hamd sadece Allah’adır. Ey Rabbimiz! Bize nurunu tamamla. Bizi affeyle. Çünkü sen her şeyi yapmaya hakkıyla kadirsin. Ey Allah’ım! Senden hayrın hepsini istiyorum, erken olanını da geç olanını da istiyorum. Senden günahlarımın bağışlanmasını diliyorum. Ey merhametlilerin en merhametlisi, senden aynı zamanda rahmetini de diliyorum. Ey Rabbim! Beni bağışla, bana rahmet et. Kusurlarımı affet, bildiğin günahlarımı da sil. Çünkü sen, bizim bilmediğimizi bilensin. Şüphesiz ki sen izzet sahiplerinin en yücesi ve en şereflisisin.\n" +
                            "Sa’y’in 4. Şavtında Okunacak Dua:\n" +
                            "Allah en büyüktür. Allah en büyüktür. Hamd sadece Allah’adır. Allah’ım, ben senden senin bildiğin hayırları diliyorum. Senin bildiğin kötülüklerden de sana sığınıyorum. Ve senin bildiğin her şey için senden bağışlanma diliyorum. Çünkü bütün gayb alemini ve bizim bilmediğimizi her şeyi bilen yalnızca sensin. Allah’tan başka ilah yoktur. Ki O Allah, tek mülk ve iktidar sahibidir, tek gerçek olan Hak’tır ve Mübin-’dir. Muhammed de Allah’ın Rasulüdür. O da her şeyi doğru söyleyen ve vaadine güvenilendir. Ya Rabbi, beni İslâm ile idayetlendirdiğin gibi, beni ondan ayırma da. Beni Müslüman olarak vefat ettir.\n" +
                            "Sa’y’in 5. Şavtında Okunacak Dua:\n" +
                            "Allah en büyüktür, Allah en büyüktür, Allah en büyüktür. Hamd sadece Allah’adır. Sen her şeyden münezzehsin. Biz sana gereği gibi, senin hakkın olduğu gibi şükredemiyoruz. Seni sana layık olan şekliyle tenzih ederiz. Ey Allahım! Bize imanı sevdir. Onu gönüllerimize, kalplerimize nakşet! Bizi, küfürden, fasıklıktan, sana isyan etmekten tiksindir. Ve bizi doğru yola erenlerden eyle. Ey rabbim! Kalbimi aç, gönlümü genişlet. Ve işlerimi de kolay eyle.\n" +
                            "Sa’y’in 6. Şavtında Okunacak Dua:\n" +
                            "Allah en büyüktür, Allah en büyüktür, Allah en büyüktür. Hamd sadece Allah’adır. Tek olan Allah’tan başka ilah yoktur. Ki O Allah, vaadına sadıktır. Kuluna yardım eder. İslâm’a düşmanlık eden grupları da tek başına hezimete uğratır ve uğratmıştır da. Allah’tan başka ilah yoktur, O’ndan başkasına da ibadet ve kulluk etmeyiz. Kafirler hoş görmese de O’nun dini en doğru dindir. Ey Allah’ım! Bana hidayet ve takva diliyorum, af ve zenginlik diliyorum. Allahım, hamd sana mahsustur. Bunu dilimizle de söylüyoruz. Bu söylediğimiz ne güzeldir.\n" +
                            "Sa’y’in 7. Şavtında Okunacak Dua:\n" +
                            "Allah en büyüktür, Allah en büyüktür, Allah en büyüktür. O’nu büyüklerin en büyüğü olarak tekbirle anarım. Allah’a çok çok şükürler olsun. Allahım! Bize imanı sevdir. Onu gönlüme, kalbime nakşet! Beni, küfürden, fasıklıktan, sana isyan etmekten tiksindir. Ve beni doğru yola erenlerden eyle. Rabbim. Bana merhamet et, beni bağışla. Bana ikram et ve sadece senin bildiklerini de affeyle. Çünkü, bizim bilmediğimizi sen elbette biliyorsun. Ve sen hiç şüphe yok ki, ikram edenlerin, affedenlerin en izzetlisisin.\n" +
                            "Bu şekilde 7. Şavttan sonra Sa’y Biter ve Dua Edilir:\n" +
                            "Ey Rabbimiz! Bizden kabul buyur. Bize afiyet ver, bizi bağışla. Sana itaat etmekte ve şükretmekte bize yardım eyle. Senden başkasını bize vekil kılma. Tam ve kamil bir iman ve İslâm’a ulaşmamız için bize yardım et. Bizi, senin razı olacağın şekilde vefat ettir. Allah’ım! Bana acı, beni yaşattığın sürece, bende kalan isyanla ilgili her şeyden uzaklaşmama yardımcı ol. Allah’ım, bana acı ki, işe yaramaz boş işlerle uğraşmayı bana zor göreyim. Beni senin razı olacağın şeylerle rızıklandır, ey merhametlilerin en merhametlisi olan Allah’ım.\n" +
                            "Sa’y’ın bitiminden sonra iki önemli durum vardır.\n" +
                            "1.\tİfrad ve Kıran Haccı yapanlar, ihramdan çıkmazlar. İfrad Haccı yapanın, yapmış olduğu bu sa’y, ziyaret tavafının sa’y’ı; Hacc-ı Kıran yapanın sa’y’ı da Umre’nin sa’y’ı olmuş olur. Hacc-ı Kıran yapanın ihramı devam ettiği için, bir Kudüm tavafı yapar, ardından da farz tavafın sa’y’ini yaparsa, Bayram günlerinde yapacağı farz tavafdan sonra sa’y yapmaz.\n" +
                            "2.\tTemettu Haccı yapanlar ise, bu sa’y ile Umre’yi tamamlamış olurlar. Traş olarak ihramdan çıkar ve tamamen helal duruma geçmiş olurlar.\n");
                } else if (((TextView) view).getText().toString() == "ZEMZEM İÇERKEN OKUNACAK DUA") {
                    in.putExtra("baslik",baslik);
                    b = "Zemzem suyu ikrâm edildiğinde, güzel kokuda olduğu gibi geri çevirmemeli, almalıdır. Su içtikten sonra Resûlullah’ın yaptığı gibi: “Elhamdü lillâhillezî ce’alehü azben fürâten birahmetihî ve lem yec’alhü milhen ücâcen bizünûbî” duâsını okumalıdır. \n" +
                            "Duâda, rahmeti ile suyu tatlı yapıp günahların sebebi ile acı bir tuz hâline getirmeyen Allahü teâlâ’ya hamd olsun denilmektedir. \n" +
                            "Zemzem ne niyetle içilirse ona faydası olur. Bunun için, şifa için, sıkıntıdan kurtulmak için, son nefeste iman ile ölmek için... Onun için niye çok ihtiyacımız varsa ona niyyet edip içmeli. Birden fazla şeye de niyyet edilebilir.Zemzem içmeyi bir nimet bilmelidir.Hadis-i şeriflerde buyuruldu ki:\n" +
                            "“Zemzem, doyurucu ve hastaya şifa vericidir.” \n" +
                            "“Zemzemi, belalardan korunmak niyeti ile içeni Allah korur.” \n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "KABEYİ GÖRÜNCE OKUNACAK DUA") {
                    in.putExtra("baslik",baslik);
                    b = " “Allah’ım! Bu mübarek Beyt’in, şerefini, azametini, keremini, heybetini, hayr ve salâhını, iman nurunu ziyade eyle. Hac ve umre niyetiyle ona yönelip gelen, onun azametini, şerefini, keremini idrak edenleri de şerefli kıl, azametini, keremini ziyade kıl, hayr ve hasenâtını, iman nurunu çoğalt… Allah’ım! Kulunum, ziyaretçinim! Ziyaret edenin ev sahibi üzerinde hakkı vardır. Sen ziyaret edilenlerin –şüphesiz- en hayırlısı, en cömerdi ve lütufkârısın. Senden, rahmetini esirgememeni, boynumuzu Cehennem ateşinden âzâd eylemeni niyaz ediyorum.\n" +
                            "Bu duânın ardından, İslâm âleminin vahdeti, kardeşlik bağları ile birbirlerine kenetlenmesi, izzet bulması, nusreti için ve bütün mü’min kardeşlerini, akraba ve yakınlarını düşünerek gönülden duâlar eder.\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "MEKKEYE GİRİNCE OKUNACAK DUA") {
                    in.putExtra("baslik",baslik);
                    b = "Allah’ım! Bu belde senin belden, bu Beyt (Kâbe-i Müşerrefe) senin beytindir. Sana geldim, rahmetini istiyorum, tâatına yöneliyorum. Emrine ittiba ederek, kaderine razı olarak, emr-i celîline teslim olarak geldim. Azabından korkan, ürperen, her zerresiyle sana muhtaçlığını bilen bir kişinin isteyişiyle beni affınla karşılamanı, rahmetinle bağışlamanı ve Cennetine girdirerek mükâfatlandırmanı istiyorum. Allah’ım! Bizlere rahmet kapılarını aç ve bizlere bu kapılardan girmeyi nasib eyle. Mel’un Şetanın tuzaklarından bizi muhafaza buyur. Allah’ım! Efendimiz Hz. Muhammed’e, ehline ve bütün sahabilerine salât ü selâm eyle!”";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "İHRAMA GİRERKEN OKUNACAK DUA") {
                    in.putExtra("baslik",baslik);
                    b = "Lebbeyk! Allahümme Lebbeyk! Ya Rab! Senin rızana şevk duyarak, rağbet ederek, kaçıp sana sığınarak, her nevî emir ve davetine icâbet edip, bütün azalarımla sana yöneliyorum. Mahlukâtın Rabbine icabet ediyorum. Hakkı hak bilip, hakka yönelerek icabet ediyorum. Kulluğumu ve kulluk vazifelerimi idrak ederek icabet ediyorum. Allah’ım! Hac ve Umre ibadetinin erkân ve âdâbına uygun olarak edâsında bana yardım eyle ve onu benden kabul buyur! Beni, emir ve nehiylerine hakkıyla icabet edenlerden eyle. Uhrevî hayattaki vaadine iman eden, emrine tabi olanlardan eyle. Kendilerinden razı olduğun, kendilerini razı ettiğin ve huzuruna kabul eylediğin heyetlerin arasında kıl!";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "MESCİDİ NEBEVİYE VARINCA OKUNACAK DUA") {
                    in.putExtra("baslik",baslik);
                    b = "Zemzem suyu ikrâm edildiğinde, güzel kokuda olduğu gibi geri çevirmemeli, almalıdır. Su içtikten sonra Resûlullah’ın yaptığı gibi: “Elhamdü lillâhillezî ce’alehü azben fürâten birahmetihî ve lem yec’alhü milhen ücâcen bizünûbî” duâsını okumalıdır. \n" +
                            "Duâda, rahmeti ile suyu tatlı yapıp günahların sebebi ile acı bir tuz hâline getirmeyen Allahü teâlâ’ya hamd olsun denilmektedir. \n" +
                            "Zemzem ne niyetle içilirse ona faydası olur. Bunun için, şifa için, sıkıntıdan kurtulmak için, son nefeste iman ile ölmek için... Onun için niye çok ihtiyacımız varsa ona niyyet edip içmeli. Birden fazla şeye de niyyet edilebilir.Zemzem içmeyi bir nimet bilmelidir.Hadis-i şeriflerde buyuruldu ki:\n" +
                            "“Zemzem, doyurucu ve hastaya şifa vericidir.” \n" +
                            "“Zemzemi, belalardan korunmak niyeti ile içeni Allah korur.” \n" +
                            "Abdullah ibni Mübarek hazretleri, (Resûlullah “Zemzem, içildiği niyete göre faydalı olur” buyurduğu için, ben de kıyamette susuzluktan kurtulmak için zemzemi içiyorum) derdi.\n" +
                            " İbni Abbas hazretleri de, zemzem içerken, “Allahümme inni es’elüke ilmen nâfian, ve rızkan vâsi’an ve şifâen min külli dâin ve sekâm.Ya Rabbi, senden faydalı ilim, bol rızık ve her türlü hastalıktan şifa istiyorum” diye duâ ederdi\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "VASITAYA BİNİNCE OKUNACAK DUA") {
                    in.putExtra("baslik",baslik);
                    b = "Bizleri hidayet yoluna, İslâma ulaştıran, en güzel selâmların üzerine olması için niyaz ettiğimiz Muhammed Mustafâ ile bize en büyük nimet bağışında bulunan Allah’a hamd olsun!\n" +
                            "“Bu vasıtaları bizlerin hizmetine amade kılan Rabbimize tesbihler olsun. O her şeyden yüce, her noksandan münezzehtir. Onun lütuf ve keremi olmadan biz bunlara güç yetiremezdik. Elbette ki biz Rabbimize döneceğiz.”\n" +
                            "Allah’ım! Yolculuğun her türlü sıkıntı ve meşakkatlerinden, çirkin bir görünüşe düşmekten, âilemize, çocuklarımıza ve mülkümüze döndüğümüzde onları kötü bir ahval içinde bulmaktan sana sığınırız. Allah’ım! Yeryüzünü katla, uzak yerleri bize yakın eyle! Allah’ım! Borca boğulup kalmaktan, şerli insanların zulmüne uğramaktan sana sığınırız. Rabbimiz! Biz bilerek veya bilmeyerek işlediğimiz suçlarla nefsimize zulmettik, bizlere mağfiret buyur. Şüphesiz ki günahları ancak ve ancak sen bağışlarsın.\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "EVDEN AYRILIRKEN OKUNACAK DUA") {
                    in.putExtra("baslik",baslik);
                    b = "Bismillah! Allah’a tevekkül ettim. Güç ve kuvvet sadece Allah’ın inâyet ve ihsanıyladır. Allah’ım! Sensin bizlerden yardımını esirgemeyecek, elimizden tutacak, haki ki yol dostu… Âilemizi, evlâdımızı, malımızı, mülkümüzü ardımızda bırakarak emanet edeceğimiz de Sensin. Allah’ım! Şu çıkmak üzere olduğumuz seferimizde senden iyilik, hayır ve hasenat, takvâ, sevdiğin ve razı olduğun ameller niyaz ediyoruz. Allah’ım! Yeryüzünü katlamanı, uzak mesafeleri bize yakın eylemeni, yolculuğumuzu kolaylaştırmanı niyaz ediyoruz. Seferimiz sırasında akıl selâmeti, din selâmeti, beden, mal, mülk, evlâd ü ıyâl selameti diliyoruz. Bizleri Kâbe-i Muazzama’yı tavaf etmek, Hac ve Umre edâ emek için Beytine ulaştırmanı, salât ü selâmın en güzelinin üzerine olması için duâ ettiğimiz Rasûlünün ziyaretini nasip eylemeni niyaz ediyoruz. Allah’ım! Ben bu yolculuğa şer için çıkmıyorum. Zulm ve kibir için çıkmıyorum. Riyâ olsun, şöhret olsun diye de çıkmıyorum.\n" +
                            "Emir ve yasaklarına uymayarak, ma’siyete / günaha bulaşarak gazabına uğramaktan korktuğum, sakındığım için çıktım; rızanı arzulayarak çıktım. Rasûlün Muhammaed Mustafa’nın (sav) sünnet-i seniyyesine uyarak,O’nun yolunun yolcusu olarak çıktım. Huzuruna varma arzu ve iştiyakıyla çıktım… Bu ibadetimi benden kabul buyur. Kullarının en şereflisi, Efendimiz Muhammed Mustafâ’ya, ehline, temiz ve nezih sahabelerine salât ü selam eyle!\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "UMRE NEDİR") {
                    in.putExtra("baslik",baslik);
                    b = "Umre kelimesi, ziyaret etmek anlamına gelmektedir. Dini bir terim olarak umre, “Belirli bir zamana bağlı olmaksızın ihrama girerek Kâbe’yi tavaf etmek, Safa ile Merve arasında sa’y yapmak ve tıraş olup ihramdan çıkmaktan” ibarettir.\n" +
                            "Umre kelimesi, ziyaret etmek anlamına gelmektedir. Dini bir terim olarak umre, “Belirli bir zamana bağlı olmaksızın ihrama girerek Kâbe’yi tavaf etmek, Safa ile Merve arasında sa’y yapmak ve tıraş olup ihramdan çıkmaktan” ibarettir.\n" +
                            "Umrenin iki farzı vardır: İhram ve tavaf. Bunlardan ihram şart; tavaf, rükündür. Vacipleri ise sa’y ile tıraş olup ihramdan çıkmaktır. Ömürde bir defa umre yapmak sünnettir.\n" +
                            "Umrenin pek çok fazileti vardır. Özellikle Ramazan ayında yapılan umrenin sevabı pek çoktur. Hz. Peygamber umre hakkında şöyle buyurmaktadır : “Umre, diğer bir umre ile arasındaki günahları siler”(7) “Ramazanda yapılan umrenin sevabı bir haccın sevabına denktir.\n" +
                            "Umre için belirli bir zaman yoktur. Her zaman yapılabilir. Ancak, Arefe günü sabahından bayramın dördüncü günü akşamına kadar yapılması mekruh görülmüştür.\n" +
                            "Umre yapmak isteyenler, gerekli hazırlıkları yaptıktan ve iki rek’at ihram namazı kıldıktan sonra, “Allah’ım! Senin rızan için umre yapmak istiyorum. Bunu kolaylaştır ve kabul eyle” diye niyet edip “telbiye” söyleyerek ihrama girerler. Bu şekilde ihrama girdikten sonra Kâbe’yi usulüne göre tavaf ederler. Nihayet Safa ile Merve arasında sa’y yaptıktan sonra tıraş olup ihramdan çıkarlar. Böylece umre tamamlanmış olur.\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "UMRE NASIL YAPILIR") {
                    in.putExtra("baslik",baslik);
                    b = "Umre Nasıl Yapılır?\n" +
                            "Umre yapmak isteyen kimse önce Medine’ye gidiyorsa, Mekke’ye hareket etmeden Medine’nin 10 km .dışındaki ZülhuleyfeMikat bölgesinde veya uçakla Mekke’ye gidiyorsa, bulunduğu otelden ihrama girerEğer hava yolu ile Türkiye’den direkCidde’ye gidip oradan Mekke’ye geçecekse Umre’ciye kolaylık olasıiçin uçağa binmeden önce havaalanında veya uçakhavalandıktan iki saat sonra ihramını giyer.\n" +
                            "İhramın Sünneti niyeti ile iki rekât narnaz kılar.\n" +
                            "1. Rekâtta Kafirun (Kulya eyyühel kafirun) 2. Rekatta İhlas (Kulhuvallahu ehad) surelerini okur. Umreyeniy et eder.\n" +
                            "Umrenin niyeti şöyledir:\n" +
                            "“Lebbeyk, Allahümme lebbeyk. Lebbeyke lâ Şerîke leke lebbeyk. İnne’l-hamde ve’n ni’mete lekeve’l-mülk, lâ Şerîkelek“\n" +
                            "‘Allahım ben umreye niyet ettim, onu bana kolaylaştır ve onu benden kabul eyle.’\n" +
                            "“Allahım, senin emrine sözüm ve özümle tekrar tekrar icabet ettim, emrine boyun eğdim. Sana ortakyoktur. Emir vedavetine gönülden ve sadakatle icabet ettim. Senin eşin ve ortağın yoktur. Şüphesiz kihamd de nimette sana mahsustur.Mülk senindir. Bütün bunlarda senin eşin ve ortağın yoktur” diyerektelbiye getirir.\n" +
                            "Niyet ve telbiyenin yapılmasıyla ihrama girilmiş ve “İHRAM YASAKLARI” başlamış olur.\n" +
                            "Yolculuk esnasında, yüksek tepelerde herhangi bir grupla karşılaştığında, konaklayıp tekrar hareketettiğinde yeni birbölgeye veya şehre girdiğinde telbiye ve tekbir getirir.\n" +
                            "Telbiye ve tekbirleri tek rakamlarla (üçer, beşer, yedişer…vs) getirmeyi tercih eder.\n" +
                            "– Hacer-ül Esved’in olduğu köşeye gelinir, çizginin üzerinde tavaf için niyet yapılır.\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "UMRENİN MANASI") {
                    in.putExtra("baslik",baslik);
                    b = "Lügatte, mamur bir yeri ziyarete niyet ve azm etmek manasındadır. Fıkıhçılar lisanında ise; Kabe-i Muazzama’yı ziyaret ve tavaf ile Safa ve Merve arasını say ederek yapılan ibadetin adıdır. Umre, sünneti müekkededir. Hac şartlarını taşıyan kimseler için vacip olduğunu söyleyen alimlerin sayısı da az değildir. Belli bir zamanı yoktur. Senenin her mevsiminde yapılabilir. Ancak Arafa ve Kurban bayramının dört gününde yapılması mekruhtur. Ramazan-ı şerif’te yapılması daha faziletlidir. Ebu Hureyre (ra) rivayet ediyor. Rasulullah (sav) Efendimiz buyurdular ki :\n" +
                            "“Umre, bir sonraki umre ile arasındakilere kefarettir. İhlasla eda edilen, riya ve masiyetten uzak bir haccın karşılığı şüphesiz cennettir.”\n" +
                            "İbn-i Abbas (ra) rivayet ediyor: Rasulullah (sav) Efendimiz ensar hanımlarından Ümmü Sinan’a buyurdular ki:\n" +
                            "“Ramazan gelince umre yap ! Onda yapılacak umrenin sevabı hac sevabına müsavidir.”\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "UMRE YOLCULUĞU HAKKINDA TAVSİYELER") {
                    in.putExtra("baslik",baslik);
                    b = "Yolculuklar günümüzde büyük imkânlar içinde yapılı¬yor olsa da yine meşakkatlidir. Uyku ve beslenme nizamı insanın kendi evinde ve çevresindeki gibi dengeli değildir. Bu yüzden birçok insan gergindir. Ancak durum ne olursa olsun mü’min her zaman olgun, fedakâr ve iyiliksever olmalıdır.\n" +
                            "• Çıkacağınız bu yolculuk sıradan bir yolculuk değildir. Evden ayrılış duâsında da zikredildiği gibi bu yolculu¬ğa şan, şöhret, rütbe, kibir ve riyâ için çıkmıyorsunuz. Eğer çıkışınız bu niyetle ise kendinize geliniz, tevbe ediniz, niyetinizi düzeltiniz, gönül safiyetine eriniz.\n" +
                            "• Bu yolculuk Allah rızasını kazanma yolculuğudur. O halde yolculuğa çıkmadan önce bu şuura eriniz. Daima sabırlı ve fedakâr olunuz. Yolculuktan kârlı dönmeyi biliniz. Dönünce de Beytullah’a ulaşmış, dünyanın dört bir yanından gelen mü’min gönüllerle sel sel olup akmış bir müslümanın şuurunu taşıyınız. Güzel söz, amel ve davranışlarla dış dünyaya güzellikler aksettiriniz.\n" +
                            "• Yolculuğa çıkmadan eşinizle, dostunuzla, yakınlarınızla, komşularınızla helalleşiniz. Evinizden sefer için iki rekat namaz kılarak ayrılınız.\n" +
                            "• Yanınıza ihtiyacınız kadar eşya alınız. Lüzumsuz eş¬yayı kendinize de başkalarına da yük etmeyiniz. Yurt dışı uçuşlarda bagaj hakkınızın kişi başı 30 kg olduğunu unutmayınız.\n" +
                            "• Yemekli olarak gidiyor olsanız bile yanınıza zarurî hallerde yenebilecek zeytin, peynir gibi kahvaltılık almanızda fayda vardır.\n" +
                            "• Sürekli kullandığınız herhangi bir ilaç var ise uygun olan, onları doktor raporu ile birlikte yanınıza almanızdır. Her ne kadar bu ilaçların aynı veya benzeri bulunacak olsa bile, zaman ve mekân onları almaya uygun olmayabilir. Ya da kendi ilacınıza daha çok güveniyor,ona karşı iç rahatlığı hissediyor olabilirsiniz. Bu hissin tedavide payı vardır.\n" +
                            "• Şeker, kalp hastalığı, böbrek yetmezliği gibi sürekli bir rahatsızlığınız varsa bu durumu kayıt sırasında şirket görevlilerine söyleyerek not ettiriniz.\n" +
                            "• Sahra (çöl) iklimine gidiyorsunuz. Gece-gündüz sıcaklık farkının yüksek olduğunu unutmayınız. Giyeceklerinizi mevsimi dikkate alarak seçiniz. Eğer hacca gidiyorsanız Mina, Arafat, Müzdelife arası intikallerde gece açıkta kalabileceğinizi hesap ederek hareket ediniz.\n" +
                            "• Yolculuk ve yapacağınız ibadetler hakkında önceden bilgi edininiz. Kitap okuyunuz ve okumak için yanınıza kitap alınız. Yaşayışla bütünleşen bilgi daha sağlam ve kalıcıdır. İbadetinizi, bilgi ve görgünüz için de kazançlı kılınız.\n" +
                            "• Uçağa, otobüslere binerken, otellere yerleşirken aceleci olmayınız, başkalarına sıkıntı vermeyiniz, kul hakkı ihlali yapmayınız. Olgunluğu siz gösteriniz. Çevrenize ve görevlilere yardımcı olunuz, onları baskı altına almaya çalışmayınız, sıkıntı kaynağı olmayınız.\n" +
                            "• Bir süre beraber bulunacağınız, birlikte ibadet edeceğiniz insanlarla gerçek dost olunuz, onlarla hasım olma gafletine düşmeyiniz.\n" +
                            "• Mekke’ye Medîne’ye vardığınızda otelinizin adres kartını, telefonunu almayı, yollar hakkında bilgi edinmeyi unutmayınız.\n" +
                            "• Vardığınız topraklar, İslâm nûrunun ilk yayılmaya baş¬ladığı, Allah Rasûlü’nün(sav) gezip dolaştığı, nice acı ve çilelere katlanıp mücadeleler verdiği ve nice hatıraların yaşandığı topraklardır. Bunun idrakinde olarak hareket ediniz.\n" +
                            "• Hac ve umreye birçok kereler gitmiş olsanız dahi ilk gidiyormuşçasına duygularınız taze ve canlı tutunuz. Gereksiz iş, manasız konuşmalarla vaktinizi hebâ etmeyiniz. Birbirinizi hayra, ilme ve irfana teşvik ediniz, bilgi alış-verişi yapınız.\n" +
                            "• Hac ve Umre sırasında kadınlar tarafından alımlı ve göze batıcı kıyafetlerin giyildiğine şahid oluyoruz. Bunun farklı bir hata olduğunu, bu beldelerde daha fazla dikkat çekici hale geldiğini unutmayınız.\n" +
                            "• Hacı ve umrecilerin, Mukaddes Diyar’da ellerinde sigara ve laubâlî tavırlarla dolaşmasının hiç de hoş olmadı-ğını biliyorsunuz. Bu hac ve umrenizi kötü alışkanlıklar ve tavırlardan kurtulma vesilesi edinilmesinin bu hatalara devamdan çok daha hayırlı olduğunu unutmayınız.\n" +
                            "• Sevap, başkasına zulmederek, acı ve sıkıntı verilerek elde edilmez. Hacerü’l-Esved’i mutlaka öpmek hırsıyla haram veya mekruh işlemeyiniz.\n" +
                            "• Şirket harici yapacağınız gezi ve ziyaretleri şirket gö¬revlilerine haber veriniz, tavsiyelerini alınız.\n" +
                            "• Şikâyetleriniz varsa arkadan söylenmeyiniz, iyi bir üslupla görevlilere haber veriniz, çözüm için yardımlaşı¬nız. Sorun olmayınız, yardımlaşan ve yardım eden olunuz, dost ve ecir kazanınız.\n" +
                            "• Bulunduğunuz yer Mukaddes Diyar Mekke’dir. Beytullah’ın yanıdır. Dünyada başka bir Kâbe yoktur. Bununfarkında olarak zamanınızı değerlendiriniz.\n" +
                            "• Mekke-i Mükerreme ve Medîne-i Münevvere’de uygun bir çerçevede ömrünüzün geçen günlerini, içinde bulunduğunuz anları, Asr-ı Saadet’te yaşananları, Hak Dâvâ’nın bizlerden istediklerini, bizim nelerle nasıl zaman geçirdiğimizi düşününüz.\n" +
                            "• Mevlâ’nın bize lütfettiği ömrün şu ana kadar nasıl bir çizgide aktığını, insanlığı, insanlığın gittiği istikameti, İslâm âleminin durumunu, İslâmın nasıl bir ümmet istediğini ve bizim istenenin neresinde olduğumuzu, şergüçlerin İblis uğruna gayretlerini, bizleri ve diğer insanları nereye doğru sürüklemek istediklerini, insanlığa ne gibi bir yarın hazırlamaya çalıştıklarını, onların karşısında bizim durumumuzu tefekkür ediniz.\n" +
                            "• Şuur derecenizi ölçünüz, bu haccınızın veya umrenizin size neler kazandırdığını düşünce süzgecinizden geçiriniz.\n" +
                            "• Bu güne kadar öğrendiklerinizi, biriken bilgilerinizi, mutlaka öğrenmeniz gerekenleri, İslâm’ın istediği bilgi, olgunluk, edep ve terbiyenizi taşıyıp taşımadığınızı iyi muhasebe edin. Bu alanda neler yapmanız gerekti¬ğine, diğer mü’min kardeşlerinizle, yakın akrabalarınız ve âilenizle nasıl ve ne şekilde bağ kurmanız ve bağlarınızı korumanız gerektiğine karar veriniz.\n" +
                            "• Gelecek günlerinizin hayırlı günler olması, Allah yolunun gerçek erlerinden sayılmanız için neler yapmanız gerektiğini düşününüz. Bütünüyle kendinizi bir muhasebeden geçirdikten sonra hayatınıza yeniden yön veriniz.\n" +
                            "• Unutmayınız ki, geride bıraktığınız hiç bir saniye bir daha geri gelmeyecektir. Kalbinizin her vuruşu mazîde kalan bir vuruştur. Onun için her zaman dilimini, katettiğiniz her mesafeyi sonradan pişman olmayacak şekilde geride bırakın. Hayat adımlarınızı iyi atın, ayak bastığınız yerleri iyi hesap edin. Yarın kimlerle haşredilmek istiyorsanız onların safında olun. Nasıl haşredilmek istiyorsanız öyle yaşayın. Kısaca ne biçmek istiyorsanız onu ekiniz.\n" +
                            "• Zaman zaman gönül limanına sığınmayı, tefekkür derinliklerine dalmayı, manevî güzelliklerden haz almayı, bize sayısız nimet bahşeden Mevlâ’ya hakkıyla şükretmeyi unutmayınız.\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "İHRAM YASAKLARI") {
                    in.putExtra("baslik",baslik);
                    b = "1.\tErkeklerin giyim eşyası olarak vücuda göre şekillendirilmiş dikilmiş veya örülmüş şeyleri giymesi.\n" +
                            "2.\tBaşını örtmesi: Takke, bere veya sarık giymesi.\n" +
                            "3.\tEldiven, çorap veya topukları kapalı ayakkabı giymesi.\n" +
                            "4.\tNOT: (Giyimle ilgili bu yasaklar sadece erkekler içindir. Kadınlar normal elbiselerini giyerler. Giydikleri elbisenin beyaz olması şartı yoktur. Yalnız yüzlerini, yüzlerine değen bir şeyle örtemezler.\n" +
                            "5.\tSaç, sakal, bıyık tıraşı olması, vücudun diğer bölgelerinden kıllar koparması, yolması, tıraş olması. Saç traşı, kıl koparmak kadınlar için de yasaktır.\n" +
                            "6.\tTırnak kesmek.\n" +
                            "7.\tGüzel koku sürünmek, kokulu sabun kullanmak.\n" +
                            "8.\tCinsi ilişki veya ilişkiye yol açan söz ve davranışlarda bulunmak.\n" +
                            "9.\tKarada yaşayan av hayvanlarını avlamak veya bunlara zarar vermek\n" +
                            "1.\tBaşkalarıyla tartışmak, kavga etmek ve kırıcı davranmak.\n" +
                            "2.\tİhramlı her zamankinden daha fazla edepli, sabırlı, güzel sözlü olmalıdır.\n" +
                            "3.\tBazı kimseler yorgunluk, sıcak, kalabalık ve cehaletin etkisiyle çok hiddetli oluyorlar. Bu ibadeti yaparken özellikle ayetlerle yasaklanmış olan bu günahları işlemek büyük gaflettir.\n" +
                            "İHRAMDAYKEN SERBEST OLANLAR\n" +
                            "•\tYıkanmak\n" +
                            "•\tKokusuz sabun kullanmak\n" +
                            "•\tDiş çektirmek\n" +
                            "•\tÇiçek ve meyve koklamak\n" +
                            "•\tYüzük ve kol saati takmak\n" +
                            "•\tÜzerine, ayaklar ve baş kapanmadan yorgan ve pike örtmek\n" +
                            "•\tİhramın beyaz olanı diğer renklerden efdaldir. İhramlı, kirlenen veya zarar gören ihram elbiselerini yenisiyle ve temiziyle değiştirebilir.\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "MEKKE GENEL BİLGİLER") {
                    in.putExtra("baslik",baslik);
                    b = "Mekke‟i Mükerreme bütün müminlerin kıblegahı, ilk vahyin indiği İslâm nurunun bütün kainata yayıldığı, hak davanın bütün karanlık çehresine karşı haykırıldığı, bu dava uğruna ilk çilelerin çekildiği nice mücadelelerin vuku bulduğu ve nice mucizelerin gerçekleştiği topraklardır. Rasulullah (sav) Efendimizin ana yurdu, İbrahim (as)‟ın dua ve insanlığı davetine mazhar olmuş bir diyardır. Kısaca her adımı hatıralarla dolu, İslâmın beş temelinden biri olan Haccın ve gönüllere tazelik veren Umre ibadetinin ifâ edildiği yerdir. Mekke‟i Mükerreme bütün müminlerin kıblegahı, ilk vahyin indiği İslâm nurunun bütün kainata yayıldığı, hak davanın bütün karanlık çehresine karşı haykırıldığı, bu dava uğruna ilk çilelerin çekildiği nice mücadelelerin vuku bulduğu ve nice mu-\n" +
                            "cizelerin gerçekleştiği topraklardır. Rasulullah (sav) Efendimizin ana yurdu, İbrahim (as)‟ın dua ve insanlığı davetine mazhar olmuş bir diyardır. Kısaca her adımı hatıralarla dolu, İslâmın beş temelinden biri olan Haccın ve gönüllere tazelik veren Umre ibadetinin ifâ edildiği yerdir. Hz. İbrahim milattan yaklaşık 2000 yıl kadar önce Irak‟ta Sümer şehrinde dünyaya geldi. Peygamber olduktan sonra halkı imana davet ettiği için güneşe ve yıldızlara tapan Babil hükümdarı Nemrut tarafından ateşe atıldı. Fakat Allah‟ın emri ile ateş onu yakmadı. Kendisine inanan İbrani kavmi ile Filistin‟e göç etti. Bir ara Mısır‟a gitti. Orada ilahi davete inanan kimse bulamadığı için tekrar Filistin‟e döndü.\n" +
                            "Kâbe\n" +
                            "Yeryüzünün ilk ibadethanesi ve haccın sebebi. Müslümanların kıblesi olan Kâbe yeryüzünde yapılan ilk ibadethanedir. Mekke şehrinde Mescid-i Haramın ortasında yaklaşık 13 metre yüksekliğinde 12 m. boyunda ve 11 m. genişliğinde taştan yapılmış dört köşe bir binadır. Kur‟an-ı Kerimde de belirtildiği gibi yer yüzünde bina edilen ilk mescittir. “Şüphesiz, âlemlere bereket ve hidâyet kaynağı olarak insanlar için kurulan ilk ev (mabet) Mekke‟deki (Kâbe)‟dir.” Kâbe‟nin inşâsı hakkında değişik rivayetler vardır. Bu rivayetlerden çıkan sonuca göre Kâbe‟yi ilk yapanlar ya melekler veya Hz. Adem‟dir. Bu konuda İbn Kesir (774/1372) şunları söylemektedir: “Kur‟an-ı Kerim‟in açık ifadesine göre Kâbe‟yi ilk inşa eden İbrahim (as) dır. Daha önce bina edildiğine dair rivayetler kesinlik ifade etmez. Bu konuda söylenecek en doğru söz şudur: Kâbe‟nin imarını emreden Cenab-ı Hak, tebliğcisi ve mühendisi Cebrail, ustası İbrahim yardımcısı da oğlu İsmail‟dir.”\n" +
                            "Hz. İbrahim Harran‟da iken amcasının kızı Sâre ile evlendi. Harran halkı İbrahim‟in dâvetine kulak asmadığı için önce Şam‟a ve daha sonra Mısır‟a hicret etti. Bir süre sonrada eşi Sâre ve cariyesi Hâcer ile Filistin‟e geldi. Çocuğu olmayan Hz. İbrahim Allah Teâla‟ya şöyle dua etmişti: “Rabbim! Bana sâlihlerden olacak bir çocuk ver, dedi. İşte o zaman biz onu uslu bir oğul ile müjdeledik.” Sanki karısı Sâre İbrahim‟in hatırından geçenleri hissetmiş gibi ona şöyle dedi: “Allah beni çocuktan mahrum etti. Cariyen Hâcer ile evlenmeni münasip görüyorum. Ola ki, Allah sana ondan bir çocuk ihsan eder.” Oldukça yaşlanmış olan Sâre kısırdı. Kendisinden çocuk umulmuyordu. İbrahim (as) Hâcer ile evlendi. Hâcer, İsmail adında bir çocuk doğurdu. İbrahim‟in yaşı 86 idi. Fakat Sâre baştan kendisi teklif etmesine rağmen Hâcer ve İsmail‟i kıskandı, onların uzaklaştırılmalarını istedi.\n" +
                            "İbrahim (as) de Cenâb-ı Hakkın emri üzerine Sâre‟nin arzusunu kabul etti ve Hâcer‟le oğlu İsmail‟i Mekke‟ye götürmeye karar verdi. Beraberce yola çıktılar ve Kâbe‟nin bulunduğu yere geldiler. İbrahim, Hâcer ve İsmail‟i susuz ve tenhâ bir vadiye yerleştirdi. Kendisi geriye dönerken Hâcer ona: “Nereye gidiyorsun? Bizi bu ıssız ve çorak vadide kime bırakıyorsun?” dedi ve bu soruyu defalarca tekrar etti. Bu arada da “Allah mı emrediyor?” deyince İbrahim: “Evet” dedi. Hâcer de: “Öyleyse Allah bizi zayi etmez.” diyerek huzur duydu ve sakinleşti. İbrahim ayrıldı, ama kalbi, eşi ve çocuklarından ayrılmıyordu. Fakat Allah‟ın isteği kendi isteğine galip geldi ve Rabbi‟ne teslim oldu. Kur‟ân‟m naklettiği şu kelimelerle dua ve niyazda bulunarak yoluna devam etti:\n" +
                            "“Ey Rabbimiz! Namazı dosdoğru kılmaları için ben, çocuklarımdan bir kısmını Senin Beyt-i Hareminin (Kâbe‟nin) yanında ekinsiz bir vadiye yerleştirdim. Artık Sen de insanlardan bir kısmının gönüllerini onlara meyledici kıl ve meyvelerden bunlara rızk ver. Umulur ki bu nimetlere şükrederler.” Hâcer de sabır ve teslimiyet içerisinde bekledi. İbrahim‟in bıraktığı yiyecek ye içecek tükendi. İkisi de susadılar. Hâcer oğlu İsmail‟in susuzluktan kıvranışına dayanamadı. Şaşkın vaziyette su aramaya koyuldu. Safa tepesine çıktı bir şey bulamadı. Merve tepesine yöneldi yine bir şey bulamadı. Böylece Safâ‟dan Merve‟ye dört, Merve‟den Safâya üç kere geldi gitti. Son seferde Merve‟ye tırmanırken bir ses işitti. Birde ne görsün! Meleklerden biri kanadı ile yeri eşiyor. Nihayet su gözüktü. Bu zemzem idi. Bu ilahi lütuf sayesinde susuzluklarını giderdiler. Su sebebi ile burası kuşlarında uğrak yeri oldu. Kuşları toplu halde hareketi yakından geçen Cürhümlü bir kafilenin dikkatini çekmişti. Kuşları takip ederek Mekke‟ye geldiler. Suyun varlığını öğrenince Hâcer‟e gelip ondan, komşu olmak için müsaade istediler. İsmail evlenme çağına gelince Cürhümlü bir kız ile evlendi ve onlardan Arapça öğrendi. İbrahim (as)‟in oğullarından ilk Arapça konuşan İsmail‟dir.\n" +
                            "Hâcer Validemiz 90 yaşlarında vefat etmişti. İbrahim (as) bazen İsmail‟i ziyaret ediyordu. Bu ziyaretlerin birisinde Cenab-ı Hak O‟na yeryüzünde ibadet edilen ilk mescit olmak üzere Kâbe‟yi bina etmesini emretti. İbrahim binayı yapmaya, İsmail de taş taşımaya başladı. Kâbe‟nin duvarları yükseldi. Cebrail‟in (as) işareti üzerine İsmail (as) Hacerü‟l-Esved‟i getirdi. Binayı ya-\n" +
                            "parlarken her defasında dua ediyorlardı. Bunu Kur‟ân-ı Kerîm şöyle anlatır: “Bir zamanlar İbrahim İsmail ile beraber Beytullah‟ın temellerini yükseltiyor (şöyle diyorlardı:) Ey Rabbimiz! Bizden bu hayırlı işi kabul et. Gerçekten sen duamızı işitici, niyetimizi bilicisin. Ey Rabbimiz! Bizi sana boyun eğenlerden kıl.\n" +
                            "Neslimizden de sana itaat eden bir ümmet çıkar. Bize ibadet usullerini göster. Tevbelerimizi kabul et. Zira tevbeleri çokça kabul eden çok merhametli olan ancak sensin.” Duvarlar yükseldikçe İbrahim (a.s) iskele olarak kullanmak üzere yüksek bir taşın üzerine çıktı. Onu iskele yaptı. Üzerinde ayak izlerinin kaldığı bu aş Makam-ı İbrahim idi. Bu taş önceleri Kâbe‟ye bitişikti. Hz. Ömer (ra) onu, tavaf sahasını genişletmek ve arkasında namaz kılan hacıları meşgul etmesin diye, Kâbe‟nin biraz gerisine aldı. Bugün Hz. İbrahim‟in ayak izini taşıyan bu taş bir muhafaza içinde, Hz. Ömer‟in naklettiği yerde ziyaret edilmektedir. Kâbe bitince oranın bakım vazifesi de Cenabı Hak tarafından İbrahim ve İsmail‟e verildi. Makamı İbrahim‟de durup Kâbe‟ye dönüldüğünde karşıya gelen ve Kâbe‟nin kuzeydoğu duvarının solunda, Kâbe‟nin kapısı (Bab-ı Mültezem) bulunmaktadır. Kâbe‟nin her köşesinin ayrı bir adı vardır ve bunlara “rükn” denir. Doğu köşesine er-Rüknü‟l-Hacer, batı köşesine er-Rüknü‟ş- Şâmî, kuzey köşesine er Rüknü‟l- Irâkî, güney köşesine ise er-Rüknü‟l Yemâni adı verilir. Sütunların üstünde Esmâ-i Hüsnâ (Allah‟ın en güzel isimleri) ile Allah‟a yakarışı ifade eden “Ya Hannân” (ey çok acıyan), “Ya Mennân” (ey çok ihsan eden) ve “Ya Deyyân (ey çok mükafatlandıran veya cezalandıran) ibaresi yazılıdır.\n" +
                            "Kâbe‟de bir de Türkçe‟de „Altın Oluk‟ diye anılan bir oluk bulunmaktadır. Bu oluk, Kâbe‟nin „Rukn-i Şâmi‟ ile „Rukn-i Irâkî‟ denilen köşeleri arasındaki kuzey batı duvarının üstünde ve bu duvarın ortasına gelecek şekilde yerleştirilmiştir. Arapçada “Mizâbü‟r-Rahme”, adı verilir. Kâbe damında biriken yağmur suları bu oluktan akmaktadır. Kâbe damına konulan ilk oluk budur. Kâbe‟nin örtüsü her yıl değiştirilir. Eski örtü önceleri Kâbe‟nin anahtarını elinde bulundurma yetkisine sahip olan Benî Şeybe‟ye mensup görevliler tarafından düzgün parçalara bölünerek hacılara dağıtılırdı. Bugün bu görev resmi yetkililerce sürdürülmektedir. Bu örtü Osmanlılar zamanında özel olarak Mısır‟da dokutturulur, Sürre alayı ile Kâbe‟ye örtülmek üzere Mekke‟ye gönderilirdi. I. Ahmed döneminden itibaren bu örtünün İstanbul‟da dokutturulmasına başlanmış ve önceleri Mısır, sonraları Şam yolu ile Mekke‟ye gönderilmiştir.\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "MESCİDİ HARAM") {
                    in.putExtra("baslik",baslik);
                    b = "Kâbe‟yi içine alan Mekke mescidine el-Harem‟ül Mekkî, Medine‟deki mescide Mescid-i Nebi, el-Haram‟ül Medenî denir. Bir saygı ifadesi olarak her ikisini belirtmek üzere Harameyn tabiri kullanılır. Kâbe-i Mazzamayı çepeçevre kuşatan etrafı kubbeli ortası açık büyük bir camidir. Ortasındaki küçük meydanınortasında bulunan Kâbe, Zemzem ve Makamı İbrahim bu caminin bir parçasını teşkil eder. Dilimizde daha çok Harem-i Şerif olarak bilinen bu mescide Mescid-i Haram da denir. Kur‟an Kerim de 16 yerde Mescid-i Haram geçmektedir. Harem-i Şerif‟te yapılacak iyilik ve kötülükler diğer beldelere göre kat kat sonuç meydana getirir. Cenab-ı Hak şöyle buyuruyor “Kim Mescid-i Haram‟da zulüm ile hak‟tan uzaklaşmaya yeltenirse, biz ona da ağır bir azab tattıracağız.” (Hac 22/25) Hadisi şerifde ise şöyle buyurulur: “Mescidi Haramda kılınacak bir namaz başka yerde kılınacak yüzbin rekat namazdan daha üstündür” Başka bir hadiste ise “Allah Teala Beytullah‟a hergün 120 rahmet gönderir. Bunun altmışı tavaf edene, kırkı orada namaz kılana, yirmisi de Kâbe‟ye bakanlara verilir” buyurmaktadır. Mescidi Haram‟da değişik zamanlarda genişletme çalışmaları yapılmıştır. En önemlisi Kral Abdülaziz zamanındakidir. Zira o Mescidi Haramın genişletilmesi için emir verdi ve mes‟a (say yapılan yer) hızlı bir çalışma ile Harem-Şerifin sınırları içine alınarak hacı ve umrecilere büyük kolaylık sağlandı. (1995) Ayrıca onun zamanında mes‟anın ikinci katı inşa ettirilmiştir. Kral Abdülazizden sonra Kral Suud, Faysal ve Kral Halid ve şimdiki Kral Fahd Haremi Şerifin genişletilmesine büyük katkıda bulunmuşlardır. Kral Fahd genişletmenin yanında aydınlatma ve güzelleştirilmesine de önem vermiştir. Onun zamanında Haremin kapıları yenilenmiş. Zemzem suyu soğutulup pompalanmış.yangınla mücadele sistemleri kurulmuş, mescidin temizliğine büyük önem verilmiştir. Son olarak elektrikli yürüyen merdivenler yapılmış ve 3. kata çıkışlar sağlanmıştır.";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "CEBELİ NUR") {
                    in.putExtra("baslik",baslik);
                    b = "Nur dağı eski adıyla Cebel-i Hıra.Hıra mağarasının bulunduğu dağ. Rasulullah (sav) Efendimizin kırk yaşlarına geldiklerinde, içine yerleşen inzivaya çekilme, ibadet ve tefekkür duygu ve arzularını gerçekleştirmek için bu dağdaki mağarayı seçmişti. Zirveye yakın, Beytullaha bakan istikamette, yönü de Kâbe‟ye yönelik bu mağaraya yerleşmiş, gönlüne yerleşen bu duyguyla insanlardan uzak bu ıssız mağarada tefekküre dalar, hanif dini üzerine ibadet ederdi. Yiyecek ve içeceği bitince Mekke‟ye gelir, Hz. Hatice validemizin hazırladığı yiyecek ve içecekleri alır ve tekrar mağaraya dönerdi. Günler bu şekilde devam ederken Ramazan-ı Şerifin 26. günü (6 Ağustos 610 M) büyük buluşma anı gelip çatmış, o seçilmiş insan bu ıssız dağda bir anda karşısında Cibril (as)‟i görmüş dehşetle ürpermişti. Kendisine “Oku” diyordu. O, ürperti içinde “ben okuma bilmem” diye cevap verdi. Ama Cibril (as) kendisini sıkıyor ve yine “oku” diyordu. O yine “ben okuma bilmem”\n" +
                            "diye cevap verdi. Cibril (as) kendisini tekrar sıkıyor ve üçüncü defa “oku” diyor ve aynı cevabı alıyordu. Peşinden “ Yaratan rabbinin ismiyle oku….” diye başlayarak Alak Suresinin ilk beş ayetini tebliğ ediyor ve gözden kayboluyordu. Ürperti ve dehşet geçmemişti. Ama ayeti kerimelerin gönlüne nakşedildiğini hissetmiş, üslup ve mana güzelliğinin lezzetini duymuştu. Böylece burada nübüvvetin ilk günleri başladı.\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "CİN MESCİDİ") {
                    in.putExtra("baslik",baslik);
                    b = "Resulullah‟ın (sav) Taiflileri İslâma davetten dönerken bu noktada Nusaybin Cinlerinden bazılarına Kur‟an okumuş olmasıdır. Bu hadise İslâmi kaynaklarda şu şekilde rivayet edilir. Peygamberimizin (sav) hanımı Hz.Hatice validemiz ve amcası Ebu Talip vefat etmişti. Her ikisinin de arka arkaya vefat etmesi Peygamberimizin (sav) iki dayanaktan mahrum kalmasına sebep oldu. Bundan sonra Kureyşliler daha çok eza ve cefa etmeye başladılar. Bunun üzerine Peygamberimizin (sav) belki İslâm dinini kabul ederler ümidiyle Taiflilere gitmiş ve onları İslâm‟a davet etmiştir. Taif Mekke‟ye 80km. uzaklıkta yüksek ve serin bir şehirdir. Ancak oradan da üzgün ve eli boş vaziyette dönmüş bir bağ bekçisi müslüman olmuştu. Mekke‟ye geldiğinde Peygamberimiz‟in (sav) üzgünlüğünü gidermek için Cenab-ı Hak Hucun denilen yerde Cinlere emretmiş ve Peygamberimizin (sav) okuduğu Kur‟an-ı Kerim-i dinlemişlerdir.\n" +
                            "Yedi kişilik bir kafile olduğu söylenen bu cinler grubunun Peygamberimizin (sav) okuduğu Kur‟an-ı dinlemesi Peygamberimizin (sav) fevkalade memnun ve mesrur etmiştir. Cinlerin Kur‟an-ı Kerim-i dinledikleri bu mekana daha sonra bir mescid yapılmıştır ve ismine de Cin Mescidi denilmiştir. Vakti olan hacı ve umrecilerin orayı ziyaret etmeleri, iki rekat namaz kılmaları ve İslâm için nice çile ve meşekkatlerin çekildiğini İslâm‟ın bizlere kolay ulaşmadığını hatırlayıp dini şuurumuzu artırması için Rabbimize dua etmeleri tavsiye olunur.\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "CENNET'UL MUALLA KABRİSTANI") {
                    in.putExtra("baslik",baslik);
                    b = "Öteden beri Mekke‟nin mezarlığıdır. Şehrin biraz dışında Hucun mevkiinde bulunan bu kabristan nice büyük sahabelerin mezarlarını barındırır. Peygamberimiz (sav) uzun yıllar beraber yaşadığı ve İslâmı ilk kabul eden kişi olma şerefine eren Hz. Hatice validemizin kabri de buradadır. Peygamberimizin amcası Ebu Talip, dedesi Abdülmuttalip ve küçükken vefat eden oğulları Tahir ve Kasım burada medfundur. Cennetü-l Mualla da ayrıca HaccacZalim tarafından hunharca şehid edilen\n" +
                            "Abdullah B. Zübeyr‟in kabri de bulunmaktadır. Abdullah B. Zübeyr cennetle müjdelenen Hz. Zübeyr b. Avvam‟ın ve Hz. Ebu Bekir‟in kızı Hz. Esma‟nın oğludur.\n" +
                            "Mescid-i Harem’in yaklaşık 1.5 km. kuzeyinde yer alan bu mezarlık aynı zamanda şehrin tarihi mezarlığıdır. Sevgili Peygamberimizin dedesi Abdülmuttalip, amcası Ebu Talip, hanımı Hz. Hatice validemiz, küçük yaşta ölen oğulları Kasım ve Abdullah’ın ve birçok Sahabi ve İslam büyüklerinin kabirleri bu mezarlıkta bulunmaktadır. Mekke’de vefat eden yerli-yabancı her Müslüman günümüzde de bu mezarlığa defnedilmektedir\n";
                    in.putExtra("rehber", b);
                }else if (((TextView) view).getText().toString() == "ZEMZEM") {
                    in.putExtra("baslik",baslik);
                    b = "Kâbe‟nin doğusunda Cenab-ı Hak‟kın Hz. Hacer ve oğlu Hz. İsmail‟e ihsan ettiği suyun adıdır. Yeryüzündeki suların en efdalidir. Bol bol içildiği gibi abdest ve gusül için de kullanılır. Hz. İbrahim Peygamber Cenab-ı Hakk‟ın emriyle Hz. Hacer ve Hz. İsmail‟i Mekke‟de bırakmış ve kendisi geriye dönmüştü. Hz. Hacer anamız yalnız kalınca güneşten korunmak gayesiyle oğlu için bir çardak yaptı ve onu altına oturttu. Ne var ki az bir müddet sonra kırbadaki su tükenmişti. Çaresiz kalan Hz. Hacer su bulabilmek için Safa ve Merve tepeleri arasında tam yedi kere gidip gelmişti. Ancak su bulamadığı gibi yorgun ve bitkin bir duruma düşmüştü. İşte bu esnada Cebrail (as) peyda olmuş ve bir kanat darbesi ile yerden su fışkırtmıştır. Tabii olarak Zemzemin ortaya çıkışı Hz. Hacer‟i çok sevindirmiştir. İçtikten ve oğluna da içirdikten sonra suyun zayi olmasından korktuğu için etrafını çevirmiştir. Bir müddet sonra Zemzem suyu kaybolmuş kuruyup gitmiştir. Bu hal Hz. Peygamber (sav)‟in dedesi Abdülmuttalip bir gece rüyasında Zemzem suyunu bulmakla vazifelendirilir. Ve zamanın müşriklerinin kurban kesme mahallinin civarında olduğu tesbit edilir.\n" +
                            "Bu yüzden Abdülmuttalip Zemzem suyunun kuyusunu kazarken çok sıkıntı çekmiştir. Ancak üçüncü gün hedefine ulaşmıştır. Bu su Allah‟ım (c.c.) büyük bir lütfudur. Ve Mekke‟nin büyüyüp bir şehir olmasını sağlamıştır. Zira Cürhumî Arapları Zemzem suyu dolayısıyla Mekke‟ye gelip yerleşmişlerdir. Zemzem, içenlere rahatlık veren rengi, kokusu ve tadıyla nefis bir sudur. Hacılar Zemzem suyunu şifa niyetine içer ve memleketlerine dönerken teberrük ve hayır kastıyla ziyaretçilerine götürür ikram ederler. Resulullah (sav) “Zemzem hangi maksatla içilirse o maksat içindir.” buyurmuştur. Bu sebeple kıyamette hesap gününde susuzluk çekilmemesi dilek ve temennisi ile içilmesi uygun olur. Yine Peygamberimiz (sav) bir başka hadislerinde “Muhakkak ki bu su mübarektir. Açın yemeği, dertlinin şifasıdır.” buyurmuşlardır. Özellikle veda tavafından sonra Beytullah‟a karşı ayakta durup, Kâbe‟ye bakarak kana kana içmek, başına ve vücuduna dökmek sünnettir.\n" +
                            "Zemzem İçerken\n" +
                            "“Allahım senden faydalı ilim, bol rızık ve her türlü dert için şifa niyaz ediyorum” diye dua edilir.\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "HECER-İ ESVED") {
                    in.putExtra("baslik",baslik);
                    b = "Kâbe‟nin güneydoğu köşesinde yerden 1.5 m. yükseklikte kırmızı damarlı, parlak, siyah renkli üç büyük ve birkaç küçük parçadan oluşan Hacer-i Esved bir çemberle çevrilmiştir. Hacer-i Esvedi Hz. İsmail‟in Cebeli Kubeys‟ten getirdiği rivayet edildiği gibi, Cebrail (as)‟ın onu semadan getirdiği de söylenir. 605 H. yılında yani peygamberimiz 35 yaşında iken Kâbe önce bir yangına maruz kaldı, arkasından da bir sel baskınına uğradı ve harab oldu. Şehir meclisi Kâbe‟nin yeniden inşasına karar verdi ve inşaat başladı. Duvarlar yükselmeye başlayıp da sıra Hacer-i Esved‟i yerine koymaya gelince ciddi bir ihtilaf çıktı. Her kabile bu şerefin kendine ait olmasını isityordu. Bunun üzerine içlerinden yaşlı birinin Safa tarafından gelecek ilk kimseyi hakem tayin etmesi teklifi kabul gördü. Oraya ilk gelen Hz. Muhammed oldu. Ondan herkes emindi. Kumaştan bir örtü getirtti, yere serdi, taşı da bu örtünün üzerine koydu. Kabile temsilcilerinden kumaşın kenarından tutup kaldırmalarını istedi. Taş istenen seviyeye gelince onu bizzat kendisi yerine yerleştirdi. Bu durum herkesi memnun etti. Hz. Peygamber (sav) Mekke‟yi fethedip Kâbe‟deki putları kırdıktan\n" +
                            "sonra tavaf ederken Hacer-i Esvede ellerini sürmüş ve onu öpmüştür.Tavafta Hacer-i Esvedin bulunduğu köşeden başlar ve orada sona erer. Tavaf esnasında Hacer-i Esved öpülür, buna imkân yoksa uzaktan elle selamlanır. Müslümanlıkta bu taşın kutsal sayılması esasen onun mahiyetinden değil, müslümanların Hz. Peygambere uymaya özen göstermelerinden kaynaklanır.\n" +
                            "Nitekim birgün Hz. Ömer (ra) bu taşa hac esnasında uzun uzun baktıktan sonra, “Aslında sen basit bir taştan ibaretsin, ne bir kimseye zarar verebilir ne de senden bir fayda gelir. Şayet Rasulullah senin önünde hürmet ve tazimde bulunmasaydı ve seni öptüğünü görmeseydim böyle birşey yapmazdım” demiştir. (Tecridi Sarih tercümesi altı 108/109) Hz. Ömer‟in bu yaklaşımı dikkate alındığında yeterli dini kültüre sahip olmayan müslümanlarm zaman zaman bir taşa ve benzeri şeylere olması gerekenin üstünde önem ve kutsiyet izafe etmeleri doğru bir davranış olmadığı anlaşılır. Hilafetin Osmanlılara geçmesinden sonra Hacer-i Esved in gümüş çerçevesi iki defa yenilendi\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "RASULULLAH'IN DOĞDUĞU EV") {
                    in.putExtra("baslik",baslik);
                    b = "Harem-i Şerif’e yakın, Beytullah’tan Bâbü’s Selâm’a doğru yönelince kapıdan çıktıktan sonra yaklaşık 200 m mesafededir. Çevresi tamamen bo¬şalmış durumdadır. Asıl evin yerine yapılmış olan betonarme bir bina, bu gün kütüphane olarak kullanılmaktadır. Burası Allah Rasûlü’nün evi olarak anılıyor olsa da Efendimiz’in evi değil, dünyaya geldiği evdir. Rasûlullah(sav) Hatice Vâlidemiz’le evlenince amcası Ebu Talib’in evinden Vâlidemiz’in evine intikal etmiş, dolayısıyla Efendimiz’in Mekke’de kendisine ait bir evi olmamıştır.\n" +
                            "Hz. Peygamberin doğduğu ev Kabe’nin doğu tarafında kalan Beni Haşim mahallesinde idi. Hz. Muhammed Miladi 20 Nisan 571 (12 Rebiulevvel) Pazartesi gecesi tan yeri ağarırken bu evde dünyaya gelmiştir. Daha sonra buradaki ev yıkılmıştır ve yerine yapılan bina günümüzde Mekke Kütüphanesi olarak kullanılmaktadır.\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "MİNA") {
                    in.putExtra("baslik",baslik);
                    b = "Mekke’nin kuzeydoğusunda Müzdelife ile Mekke arasında kalan geniş bölgeye Mina denir. Cemerat ismiyle bilinen şeytan taşlama yerleri, Hac kurbanlarının kesildiği mezbahaneler ve sevgili Peygamberimizin Mina günlerini geçirdiği mekâna yapılan Mescid-ül Hayf burada bulunmaktadır. Müzdelife vakfesinden sonra hacılar Mina’ya gelerek Hacc’ın vaciblerinden olan ve üç gün devam eden şeytan taşlama görevini burada yerine getirirler. Ayrıca bu günlerin gecelerini Mina’da geçirmek Hacc’ın sünnetlerindendir.\n" +
                            "Mina Müzdelife ile Mekke arasında, Mekke istikametinde Akabe vadisinin başlaması ile son bulan dağlarla çevrili bir sahadır. Taşlama yapılan cemrelerin bulunduğu yerdir. Hacda geceleri burada gecelemek sünnettir. Mescidi Hayf buradadır. Hz. İbrahim oğlu İsmail‟i kurban etmek için bu mıntıkaya getirmiştir. Rasulullah (sav) Medinelilerle buluştuğu akabe vadisi de buraya bilhassa büyük cemreye yakındır. Buluşmanın 1. ve 2. akabe biatlarının yapıldığı yerde Biat Mescidi diye anılagelen küçük bir cami vardır.\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "MÜZDELİFE") {
                    in.putExtra("baslik",baslik);
                    b = "Mina ile Arafat arasında bulunan 12 km2 genişliğindeki bölgeye Müzdelife denir. Yüce Allah bu meydanda bolca ibadet etmemizi emir buyurmuşlardır. Hacc’ın vaciblerinden olan Müzdelife vakfesi bu meydanda gece konaklayarak yapılır. Akşam vakti Arafat’tan yola çıkan Hacılar, akşam ve yatsı namazlarını yine bu meydanda kılarlar. Şeytan taşlama da kullanılacak taşlar da buradan toplanır. Bayramın birinci günü sabah namazından sonra Müzdelife’den Mina’ya hareket edilir.\n" +
                            "Müzdelife, Arafat‟la, Mina arasında Minaya yakın geniç bir alandır. Arafat‟tan güneş batınca buraya gelinir akşam ile yatsı namazları yatsı vaktinde burada cem edilir. Meş‟ari‟l-Haram bu sahanın ortasındadır. Ana cemaat burada namaz kılar.Cemrelere atılacak taşlar buradan toplanması en uygun olandır. Hacılar sabah namazını burada eda ederler, vakfelerini yaparlar. Müzdelife Vakfesi vaciptir. Müzdelife ile Mina arasında Muhassar denilen vâdi vardır. Ebrehenin Kâbe‟yi yıkmaya gelen fiili ordusu bu vadide sürüler halinde kuşların attığı taşlarla helak edilmiştir.Onun için bu vadi süratlice geçilir.\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "ARAFAT") {
                    in.putExtra("baslik",baslik);
                    b = "Sözlükte “bilme, tanıma, anlama ve güzel koku” anlamlarına gelen a.r.f. kökünden türeyen “Arafat”, Mekke’nin 25 km. güney doğusunda ova görünümünde düz bir alanın adıdır. Doğu, kuzey ve güneyi dağlarla çevrilidir. Arafat, Hıll bölgesinde Harem sınırları dışında kalır. Harem sınırı ile Arafat arasında Urene vadisi vardır. Haccın rükünlerinden biri olan vakfe burada yapılır. Vakfenin zamanı, Zilhicce ayının 9. günü güneşin zevalinden sonra burada başlar, ertesi günü şafak vaktine kadar devam eder. Burada kısa bir süre de kalınsa vakfe yapılmış olur. Arafat’ın tamamı vakfe mahallidir (Müslim, Hac, 149). Arafatta vakfe yapılmadan hac görevi tamamlanmaz. Peygamberimiz (a.s.) “Hac, Arafat’tır” buyurmuştur (Ebû Davut, Menasik, 68) Arafat kelimesi Kur’ân’da bir âyette geçmiştir. “Arafat’tan ayrılıp (seller gibi Müzdelife’ye) akın edince Meş’ar-i Haram’da Allah’ı anın.” (Bakara, 2/198) Arafat’ın ortasında “Cebel-i Rahmet” (rahmet dağı), batısında Nemîre Mescidi vardır. Arafat, ağaçlandırılmış ve dokuz oto yol ile Müzdelife’ye bağlanmıştır.\n" +
                            "Mekke-i Mükerreme‟nin doğusunda Hareme 20-22 km mesafede geniş düz bir sahanın ismidir. Zilhicce ayının 9. günün hac için vakfe burada yapılır. Bu vakfe haccın ilk rüknüdür. Peygamberimiz vakfesinin Cebeli Rahmenin önlerinde kıble istikametine yakın bir yerde yapmış ve veda hutbesini burada irad etmiştir. İlk ve son haccı olan veda haccında öğleyle ikindi namazını birleştirerek Mescidi Nemire‟nin bulunduğu yerde kılmıştır. Mescidi Nemirenin diğer adı, Mescidin Arafat kıble istikametinde Urena Vadisi bulunduğu içinde Mescidi Urene‟dir. Urene Vadisi Arafattan değildir. Arafat, Mekke Harem sınırları dışındadır.\n";
                    in.putExtra("rehber", b);
                }else if (((TextView) view).getText().toString() == "CEBEL-İ SEVR") {
                    in.putExtra("baslik",baslik);
                    b = "Peygamberimizin Mekke‟den Medineye giderken saklandığı mağaranın bulunduğu dağ. Mekke yakınlarında haremi şerifin güney kısmındadır. Peygamberimiz burada Hz. Ebubekir ile üç gün kalmışlardır. Buradan henüz müşrik olan yol rehberi Abdullah b. Üreykıt rehberliğinde batıya doğru yönelerek, sonra da kuzeye dönerek sahil yakınlarından Medineye doğru yola çıkmışlardır. Mağarada kalındığı sürede Hz. Ebubekir‟in yanında çalışan Amir b. Füheyre güttüğü sürüler ile izleri kapatmış ve süt ihtiyaçlarını karşılamıştır. Hz. Ebubekir‟in oğlu Abdullah çocuk yaşta iken Mekke‟de konuşulanları aktararak onlara yardım etmiş, kızları Hz. Esma yiyecek ve içecek taşımışlardır.\n" +
                            "Bütün tedbirlere rağmen müşrikler mağara önlerine kadar gelmeyi başarmışlardır. Hz. Ebubekir‟in tereddütleri karşısında Rasulullah “Üzülme Allah bizimle beraberdir” diye teselli etmiştir. Cenab-ı Hak Rasulullahı korumuş örümcekle mağaranın önü kapanmış ve güvercinler yuva yapmışlardır. Bunu gören müşrikler burada insan yaşamıyor diyerek ayrılmışlardır.\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "RAVZA-İ MUTAHHARA") {
                    in.putExtra("baslik",baslik);
                    b = "Ravza, bahçe ve cennet anlamlarına gelir. Ravza-i Mutahhara geniş anlamıyla, âlemlerin Efendisi Hz. Muhammed (s.a.s)’in medfün bulunduğu yer ve Mescid-i Nebi demek ise de, özel manasıyla Mescid-i Nebi’nin içinde Hz. Peygamber (s.a.s)’in kabr-i saadetleriyle minber-i şerif arasında kalan kısım demektir. Bu yer 10 m. genişliğinde ve 20 m. uzunluğunda 200 m2 lik bir sahadır. Bu alanın fazileti ile ilgili olarak Allah Resulu şöyle buyurur: “Evimle minberim arası, Cennet bahçelerinden bir bahçedir”\n" +
                            "MESCİD-İ NEBİ içerisinde, Peygamberimizin kabr-i şerifi ile mescidin o zamanki minberi arasındaki yerdir. Peygamber Efendimizin: EVİMLE MİNBERİM ARASI, CENNET BAHÇELERİNDEN BİR BAHÇEDİR buyurarak medh ettiği Ravda-i Mütahhara’nın uzunluğu 22 metre, genişliği ise 15 metredir. İçerisinde Peygamber Efendimizin namaz kıldığı mihrabın da bulunduğu bu beyaz sütunlu kısım, Mescid’in diğer bölümlerinden ayrılmıştır. Öteki kısımların sütunları vehalı renkleri ayrı olduğu için rahatça bilinebilmektedir.\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "MESCİDİ NEBEVİ") {
                    in.putExtra("baslik",baslik);
                    b = "Medine-i Münevvere\n" +
                            "Resulullah (s.a.s)’ın Medine’ye hicretinden hemen sonra ashabıyla birlikte bina ettiği mescit. Bu mescit, Mescid-i Resul, Mescid-i Şerif, Mescid-i Saadet ve Mescid-i Nebevi adlarıyla da anılmaktadır. Mescid-i Haram ve Mescid-i Aksa’dan sonra yeryüzündeki mescitlerin en faziletlisidir.\n" +
                            "Resulullah (s.a.s), Hicret yolculuğunda kısa bir müddet Medine’nin dışında bulunan Kuba köyünde kalmıştı. Bu esnada Kuba mescidi adıyla bilenen mescidi inşa ettirmişti. Buradan yola çıkıp, Medine’ye girdiği zaman, Resulullah (s.a.s), misafir edip ağırlama şerefine nail olabilmek için herkes birbiriyle yarışa girmişti. Kendisini davet edenlere Resulullah (s.a.s); “Bırakın deve serbestçe yürüsün. O bizi Allahın razı olacağı bir yere kadar götürecektir” diyordu. Deve bir süre yürüdükten sonra, iki yetim kardeşe ait boş bir arsaya çöktü. Buraya evi en yakın olan Ebu Eyyub el-Ensari, Resulullah (s.a.s)’ın eşyalarını alıp sevinçli bir halde evine taşıdı (bk. Hicret mad.).\n" +
                            "Resulullah (s.a.s)’ın devesinin çöktüğü bu arsa sahipleri olan Neccaroğullarından Sehl ve Suheyl hibe etmek için ısrar ettilerse de Resulullah (s.a.s) bunu kabul etmedi ve on dinar gibi sembolik bir meblağ karşılığında burayı satın aldı. Bu bedeli Hz. Ebu Bekir (r.a) ödedi.\n" +
                            "\n" +
                            "İbn Sa’d, Resulullah’ın Medine’ye hicretinden önce Esad ibn Zurare’nin arkadaşlarıyla burada namaz kıldığını, ayrıca cuma namazlarını da burada kıldırdığını nakletmektedir. Etrafı çevrili olan bu arsanın hemen bitişiğinde, cahiliye insanlarının gömülü bulunduğu bir mezarlık vardı. Resulullah bu mezarlığın kaldırılmasını istedi. Böylece mescidin inşa edileceği arsa genişletilmiş oldu. Ayrıca burada bulunan su birikintisi de yok edildi (Nesai, Mesacid, 12; İbn Sa’d Tabakatül-Kübra, Beyrut, t.y, I, 239).\n" +
                            "Bu arsa üzerinde hemen bir mescit bina edilmeye başlandı. Ensar, Muhacir ve diğer gönüllü kimselerin de katıldığı kalabalık bir işçi-usta topluluğu tarafından yürütülen çalışmalar sonunda mescit, kısa sürede bina edildi. Resulullah (s.a.s) çalışmaları idare edip, mescidin kıble tarafındaki temellerinin atılması ve diğer planlamaları yapmakla yetinmeyip, çalışmalara bir işçi gibi taş, kerpiç taşıyarak katılmıştır. O, bu çalışmalar esnasında şu beyitleri söylüyordu: “Allahım! Ahiret hayatından başka hayat yoktur. Ensara ve muhaciruna mağfiret et” (İbn Sa’d a.g.e., I, 239-240).\n" +
                            "Temeller toprak seviyesine kadar taş, zeminden yukarısı ise kerpiç kullanılarak bina edildi. Temel yaklaşık olarak bir buçuk metre derinliğinde açılmıştı.\n" +
                            "Eni-boyu yüzer zıra (bir zıra =kırkbeş santim) olmak üzere, kare şeklinde inşa edilen mescidin mihrabı Beytu’l-Makdis yönüne denk düşecek şekilde kuzey duvarında işaretlenmişti. Üç tane kapıdan biri güney tarafındaki arka duvarda, ikincisi batı tarafındaki duvarda, üçüncüsü ise Resulullah (s.a.s)’in hücrelerinin bulunduğu doğu tarafında idi. Bu kapıya Cibril kapısı denirdi.\n" +
                            "Resulullah (s.a.s), ilk önceleri bir hurma kütüğü üzerine çıkarak hutbe okurdu. Bir zaman sonra bizzat Resulullah (s.a.s)’ın isteği veya ashabın, cemaatın kalabalıklaştığını ve arkadakilerin hutbe okurken onu göremediklerini bildirmeleri üzerine, bir kaç basamaklı bir minber yapılarak, mescite yerleştirildi (Buhari, Cuma, 26; İbn Sa’d, a.g.e., I, 250-251).\n" +
                            "Hicretten on altı ay sonra Kıblenin yönü Beytullah tarafına çevrildiği zaman, güneydeki kapı kapatılarak, burası mihrab yapıldı, Kuzeydeki duvarda da bir kapı açıldı. Mescitte namaz kılınan yerin üzeri açıktı. Ancak mescitin ortasında, hurma ağacından yapılan direkler üzerinde, hurma, dal ve yapraklarından bir gölgelik yapılmıştı.\n" +
                            "Mescitin doğu tarafında duvara bitişik olarak Resulullah (s.a.s)’in hanımları Hz. Âişe (r.anh) ve Hz. Sevde (r.anh) için, iki oda inşa edilmişti. Ayrıca yine mescite bitişik olarak, gündüzleri bir eğitim-öğretim yeri, geceleri ise, evsiz kimseler ve misafirlerin barınması için “Suffa” denilen üzeri kapalı bir bölüm eklenmişti. Resulullah (s.a.s)’e ait odalara, zamanla yedi oda daha eklenerek oda sayısı dokuza çıkmıştır. Bunların hepsi kerpiçten idi (İbn Sa’d, a.g.e., I, 499).\n" +
                            "Medine’de inşa edilen bu mescit aynı zamanda, kurulan İslam devletine ait bütün faaliyetlerin yürütüldüğü bir merkez niteliğinde idi. Resulullah, ashabıyla orada istişare eder, savaş ve barış kararlarını orada alır, elçi heyetlerini orada kabul eder, savaşa çıkacak orduları orada techiz ederek yola çıkarır, topluma ait bütün meseleler orada çözüme kavuşturulur, hatta gerektiğinde suçlular ve esirler bağlanmak suretiyle orada hapsedilirdi (Nesei, Mesacid, 20).\n" +
                            "Eğitim-öğretim faaliyetleri, mescitin “Suffa” denilen kısmında yerine getiriliyordu. İslam ümmetinin nüvesini oluşturan Ashab ve seçkin sahabe alimler, İslamda ilk üniversite sayılabilecek bu mekanda yetişmişlerdi. İslam’ın esaslarını öğrenmek üzere Medine dışından gelenler için aynı zamanda bir yatakhane vazifesi görüyordu (İbn Sa’d a.g.e., 255). Bir defasında, Temim kabilesine mensup yetmiş kişi burada barındırılmış idi (Ahmed b. Hanbel, III, 371).\n" +
                            "Resulullah (s.a.s), burada bizzat dersler veriyordu. Ancak, yeni gelen ve başlangıçta olan öğrencilere okuma yazmayı ve Kur’an-ı Kerim’i öğreten diğer öğretmenler de bulunmakta idi. Medine’den ve uzak yerlerden olmak üzere burada okuyan öğrencilerin dört yüz kişi gibi bir sayıya ulaştığı oluyordu. Burada barınanların ihtiyaçlarının büyük bir bölümü, cömert sahabeler tarafından karşılanmaktaydı (M. Hamidullah, İslam Peygamberi, İstanbul, 1980, II, 832).\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "CENNETÜL BAKİ") {
                    in.putExtra("baslik",baslik);
                    b = "Medine-i Münevvere’nin mezarlığıdır. Bu mübarek kabristanda Peygamber Efendimizin amcası Hz. Abbas, torunu Hz. Hasan, damadı ve üçüncü halife Hz.Osman-ı Zinnureyn, halası Hz. Safiye, çocuğu Hz. İbrahim, kızı Rukiye, Fatıma vemübarek hanımları başta olmak üzere sahabe ve tabiundan birçok zevat medfundur.\n" +
                            "Bukabristandaki türbeler ve mezar taşları, Medine-i Münevvere, Osmanlı idaresinden çıktıktan sonra yıktırılmıştır. Şimdi etrafı duvarlarla çevrili olan bu kabristan bir tarla görünümündedir. Kıble yönüne göre Mescid-i Nebi’nin soltarafında, hemen yan tarafındadır\n" +
                            "Mescidi Nebevi‟nin doğusundadır.Asrı saadetten bu yana kabristanlıktır. On bin civarında sahabinin yattığı biliniyor. Burada medfun bulunanların arasında Hz. Osman, Hz. Abbas, Peygamberimizin halası Safiye, zevcelerinin ekserisi, kızları, oğlu İbrahim, süt kardeşi Osman İbn‟i Maz‟un vardır. Ayrıca Mescidi Nebi çevresinde Mescidi Gamame, Mescidi Ebubekir, Mescidi Ömer, Mescidi Osman, Mescidi Ali, Mescidi Bilal, Mescidi Ebuzer… gibi mescidlerde bulunmaktadır.\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "KUBA MESCİDİ") {
                    in.putExtra("baslik",baslik);
                    b = "Peygamberimiz Hz. Muhammed, Mekke’den Medine’ye hicretleri esnasında, Medine’ye 5 km. mesafede bulunan Kuba’da 14 gün kalmıştı. Bu süre içinde Peygamberimiz orada bir mescid inşa etti ve burada namaz kıldı. Kur’an-ı Kerim’de takva üzere yapıldığı bildirilen ve İslâm âleminde cemaatle namaz kılınmak için yapılan ilk mescid budur.\n" +
                            "Kuba Mescidini ziyaret etmek ve burada iki veya dört rekat namaz kılmak müstehaptır. Bu mescidin ziyareti ile ilgili olarak Hz. Peygamber şöyle buyurmaktadır: “Kim evinde güzelce temizlenip abdest aldıktan sonra, başka maksatla değil de sadece namaz kılmak için Kuba Mescidine giderse umre sevabı alır.”\n" +
                            "Hz. Peygamber sağlığında, Cumartesi günleri Kuba Mescidini ziyaret eder ve burada namaz kılardı.\n" +
                            "Rasulullah (sav) Efendimiz, Medineye hicretleri esnasında Medine yakınlarındaki Kuba köyünde konaklamış burada bir müddet misafir olarak kalmış, bu esnada Kuba Mescidini bina etmişlerdir. Kur‟ân-ı Kerim‟de “takva üzerine kurulu mescid” diye övülen bu mescidi ve “temizliği sevenler” olarak övülen, temiz ve misafirperver Kubalıları Peygamberimiz bilhassa Cumartesi günleri ziyaret eder, onların gönüllerini hoş ederdi.\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "KIBLETEYN MESCİDİ") {
                    in.putExtra("baslik",baslik);
                    b = "İslam’ın ilk yıllarında namazlar, Kudüs’te bulunan Mescid-i Aksa’ya doğru kılınıyordu. Peygamber Efendimiz Kıble’nin Kâbe olmasını, yani namazların Kâbe’ye dönülerek kılınmasını çok arzu ediyor ve bu konuda Allah’tan gelecek emri bekliyordu. Hicretten 18 ay kadar sonra Şaban ayının 15. günü (Berat Kandilinde) Hz. Peygamber, Seleme oğulları mahallesinde öğle veya ikindi namazının farzını kıldırdığı esnada, ikinci rekatın sonunda aşağıdaki âyet-i kerime indi:\n" +
                            "“… Seni elbette, hoşlanacağın kıbleye döndüreceğiz. O halde hemen Mescid-i Haram’a (Kâbe’ye) doğru dön. (Ey mü’minler) siz de nerede olursanız olun, (namazda) oraya doğru dönün.”\n" +
                            "Bunun üzerine Hz. Peygamber, namazı bozmadan hemen Kâbe istikametine döndü, cemaat de saflarıyla birlikte döndüler. Böylece Kudüs’e doğru başlanan namazın son iki rekatı Kâbe’ye yönelinerek tamamlandı. İşte bu bakımdan bu mescide Mescid-i Kıbleteyn (İki Kıbleli Mescid) denir. Bu mescidin yerinde şimdi büyük bir cami yapılmıştır. Bu camii ziyaret edilerek iki veya dört rekat Tahiyyet’ül-Mescid namazı kılınması ve dua edilmesi güzel olur.\n" +
                            "Hicretten önce ve hicretin ilk yıllarında namaz için kıble Kudüsteki Beyt‟ül Makdis idi. Peygamberimiz Mekkede iken namazlarını daha ziyade Rüknü Yemani tarafında kılar, oradan Beyti Makdise döner ve Kabeyi böylece araya alırdı. Medineye varınca Mekke güneyde Kudüs kuzeyde kaldığı için bu mümkün olmadı. Gönlü hep Beytullah‟ı arzu ederdi. Ama emir gelmediği için kıble edinemi-\n" +
                            "yordu. Nihayet hicretten 16-17 ay sonra “Ey Rasulüm; yüzünü semaya doğru çevirip durarak bir arayış içinde olduğunu görüyoruz. Seni gönlüne hoş gelecek, arzu edegeldiğin kıbleye döndürüyoruz. Yüzünü artık Mescidi Harama çevir, Beytullah‟ı kıble edin” ayeti nazil oldu. Böylece kabeye doğru namaz kılmaya başlandı. Aynı zamanda iki kıbleye yönelindiği için bu mescid İki Kıbleli Mescid olarak anılmıştır.\n";
                    in.putExtra("rehber", b);
                }else if (((TextView) view).getText().toString() == "UHUD") {
                    in.putExtra("baslik",baslik);
                    b = "Uhud, Medine‟nin kuzeyinde, Mescidi Nebeviye yaklaşık 5 km. mesafededir.Rasulullah (sav) “Uhud bizi sever bizde Uhudu severiz” diye sevgisini gösterdiği dağdır. Uhud gazvesi hicri 3. yılda şevval ayının ortalarında İslâm orduları ile Bedir gazvesinin öcünü almak isteyen Mekke müşrikleri arasında yapılmış, büyük bir imtihana sahne olmuş, savaş kazanılmışken okçuların zafer neşesi ile Rasulullahın kesin emrine rağmen yerlerini terketmesi, başlarındaki emirin ikazlarına uymamaları sebebiyle aleyhe dönüşmüş, sahabilerden 70 kişi şehid olmuş, Peygamber Efendimiz ise yaralanmıştır. Alınan ağır darbeye rağmen şahsi azim ve gayretlerin de tesiriyle İslâm ordusu yeniden toparlanmış, müdafa harbine geçilerek, müşriklerden gelecek daha büyük zarar savuşturulmuştu. Şehidler arasında Peygamberimizin amcası Hz. Hamza, İslâm‟ın ilk davetçisi Mus‟ab İbni Umeyr de vardı. O günden sonra Okçular Tepesi olarak anılan tepe Uhud dağının Medineye bakan tarafındadır. Bu tepe ile Uhud yamaçları arasındaki vadi yaklaşık” 1 km. enindedir. Savaş bu sahada cereyan etmiştir. Şehidlik de buradadır. Okçular tepesine daha yakındır.\n" +
                            "Medine’nin 5 km. kadar kuzeyinde bir dağın adıdır. Hicretin üçüncü yılında (M.625) müslümanlarla müşrikler arasında burada yapılan savaşta, Ashab-ı kiramdan 70 kişi şehid olmuş ve buraya defnedilmişlerdir. Peygamberimizin amcası ve şehidlerin efendisi Hz.Hamza da bunlar arasındadır. Hz.Peygamber, her yıl Uhud şehitlerini ziyaret eder ve onlara dua ederdi. Uhud şehitlerini ziyaret etmek de müstehaptır. Uhud şehitleri de ziyaret edilirken selâm verilir ve dua edilir. Arzu edenler Diyanet İşleri Başkanlığının hacılara hediye ettiği Kutsal iklimde Dua kitabındaki “Mezarlık ziyaretinde okunacak selam ve duayı ” okuyabilirler.\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "CUMA MESCİDİ") {
                    in.putExtra("baslik",baslik);
                    b = "Peygamber Efendimiz’in Kuba’ya Pazartesi günü öğle sıralarında ulaştığı, Pazartesi, Salı, Çarşamba ve Perşembe günleri burada konakladığı, Cuma günü öğle yakınları buradan ayrılarak Medîne’ye doğru yola çıktığı nakledilir. Biraz ilerleyip Beni Sâ¬lim (İbn Avf) topraklarına gelince, “Rânûna” denilen vâdide Cuma vakti girmişti. Peygamberimiz Medîne’de ilk Cuma namazını burada kıldı. Onun ilk Cuma namazı kıldığı bu yere yapılan mescid, Cuma Mescidi olarak şöhret buldu. Medine’den Kuba’ya giderken, Kuba yakınlarında yolun solundadır. Kuba Mescidinin kuzeyinden görülmektedir.  Mescid-i Atike (Vadi) adıyla da anılan bu cami, Kuba caddesinde Mescid-i Kuba’ya 350 m. uzaklıktadır. Hicret sırasında Kuba’ya ulaşarak burada Mekke’den gelecek olan Hz. Ali ve diğer muhacirleri beklemek üzere bir süre kalan ve 24 Eylül 622 Cuma günü Yesrib’e hareket eden Hz. Peygamber cuma vakti girince Ranuna vadisinde Salim b. Avf kabilesine misafir oldu; buradaki namazgahta ilk cuma hutbesini okuyup namazı kıldırdı. Daha sonra bu ilk cuma namazının hatırasını yaşatmak için Mescid-i Cum’a adıyla meşhur olan bir mescid yaptırıldı.\n" +
                            "Mescid-i Atike (Vadi) adıyla da anılan bu cami, Kuba caddesinde Mescid-i Kuba’ya 350 m. uzaklıktadır. ilk defa Ömer b. Abdülazız’in Medine valiliği sırasında inşa edilen Mescid-i Cum’a, Osmanlı padişahlarından II. Bayezid tarafından yeniden imar edildi. Mihrabının yakınında Hz. Peygamber’in namaz kıldığı yer belirgin hale getirildi. Daha sonra ufak çaplı onarımlar geçiren Mescid-i Cum’a 1992’de yıktırılarak yeniden inşa edilmiştir. (Hicaz Albümü, Diyanet İşleri Başkanlığı) Türk mimarisini andıran yapısıyla arzı endam eden bu mescid Kuba Mescinin bir km. kuzeyine düşmektedir. Mimarı Mahmut Kirazoğlu’dur.\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "YEDİ MESCİDLER") {
                    in.putExtra("baslik",baslik);
                    b = "Hendek Gazvesi sırasında karargah kurulan saha Mesâcid-i Seb’a (Yedi Mescidler) diye de anı¬lır. Ancak bu mescidlere “Fetih Mescidleri” denmesinin daha uygun olduğuna inanıyoruz. Yahudilerin tahrikiyle harekete geçen ve çevre kabilelerle de anlaşan Mekkeli müşrikler, mü’min mücahidlerin üç katından daha fazla bir güçle savaş hazırlıkları yaparken; müdafaada kolaylık olur diye Selmân-ı Fârisî’nin(ra) teklifi üzerine, anlaşmalı arazîden, dağlık ve taşlık bölgeden geri kalan açık bölgeye, bütün meşakkatlere ve yokluğa göğüs gererek kısa zamanda büyük bir hendek kazılmıştı. Medine’nin kuzey doğusundan batısına kadar uzanan Harratü Vâkım ile Bathan Vâdisi arasında yer alan bu hendeğin en zayıf noktası, Sel’ Dağı önlerinde bırakılmış, karargahlar da buraya kurulmuş, düşman buranın karşısında yer almaya zorlanmış, burada karşılanmıştı. Mescidler, karargah noktalarına sonradan, (Hicrî birinci asrın sonlarına doğru Ömer İbn Abdülaziz’in Medîne valiliği sırasında) bina edilmiştir. Daha sonra Osmanlılar tarafından yenilenmiş ve sağlamlaştı¬rılmıştır. Bu mescidlerden kıble istikametine dönüldüğünde en geride olan ve Sel’ Dağının yamacında yüksekçe bir noktada yer alanın adı Mescid-i Fetih’tir. Rasûlullah(sav) Efendimiz’in merkez karargahı burada kurulmuş, burada duâ ve niyazda bulunmuş, mü¬cadelenin birçok safhalarını buradan takip etmiştir. Oradan kıble istikametine doğru basamaklara inildiğinde ilk gelinen mescid, Selmân-ı Fârisî Mescidi’dir. Onun önünde de Hz. Ali Mescidi yer alıyordu.\n" +
                            "Bu mescid H. 1414 (M. 1993) yılında yeniden yapılma niyetiyle yıkıldı. Önce kazı yapıldığını gördük, sonra bu kazı durduruldu, daha sonra da açılan yer kapatılıp asfaltla örtüldü. Zannediyoruz ki fikir değiştirilmişti. Çok geçmeden mevcut mescidlerle Sel’ Dağı arasına oldukça büyük bir câmi inşa edildi. Selmân-ı Fârisî mescidinden kıbleye doğru biraz daha ilerleyince sahanın ortalarına yakın bir yerde, düz zeminde Hz. Ömer Mescidi yer alır. Bu mescid günümüzde varlığını korumaktadır. Hz. Ömer Mescidi’nden biraz sola dönerek kıble istikametine ilerleyip, önümüze çıkacak merdivenlerden Sel’ Dağı’nın bu yöndeki yamacına tırmandığımızda karşımıza çıkacak mescid, Hz. Ebubekir mescididir. Hemen hemen Fetih Mescidi ile aynı yükseklikte ve onunla karşı karşıyadır. Buradan inilip Hz. Ömer Mescidi’nin kıble istikametine doğru yaklaşık 30 m ilerlendiğinde, Sel’Dağının bu yönde düzleştiği noktada Sa’d İbn Muaz Mescidi yer alır. Üstü açık küçücük bir mescid idi. Yan duvarları yıkılarak ortadan kaldırıldı. Halen halk tarafından buranın mescid olduğu bilinmekte ve açıkta da olsa namaz kılınmaktadır. Özellikle İranlılar tarafından bu mescid, Fatıma Mescidi olarak tanınıyor ve yakın ilgi görüyorsa da bunun doğru olmadığı kanaatindeyiz. Çünkü Fatı¬ma Vâlidemiz Uhud Gazvesine gelmişse de Hendek Gazvesinde bulunmamıştır. Bu meydanda yer alan mescidlerin yedi değil altı olduğu, hiç bir devirde de yedi olmadığı bilinmektedir. O halde niçin Yedi Mescidler diye anılıyor? sorusuna cevap arandığında, bu ismin çok sonraları dillerde dolaşmaya başladığı, belki yedinci mescid olarak, güney istikamette yakınlarda yer alan Benî Haram Mescidi’nin veya Uhud tarafına doğru Sel’ Dağı’nın uzantısı olan ve Râye Tepesi üzerinde yer alan Mescid-i Râye’nin düşünülmüş olabileceği söylenmiştir.\n";
                    in.putExtra("rehber", b);
                } else if (((TextView) view).getText().toString() == "HAC NEDİR") {
                    in.putExtra("baslik", baslik);
                    b = "";
                }
                else if (((TextView) view).getText().toString() == "HACCIN MANASI") {
                    in.putExtra("baslik", baslik);
                    b = "";
                }
                else if (((TextView) view).getText().toString() == "UMRE İLE HAC ARASINDAKİ FARKLAR") {
                    in.putExtra("baslik", baslik);
                    b = "";
                }
                else if (((TextView) view).getText().toString() == "HAC İÇİN İHRAMA GİRİŞ VE ARAFATA ÇIKIŞ") {
                    in.putExtra("baslik", baslik);
                    b = "";
                }
                else if (((TextView) view).getText().toString() == "ARAFAT VAKFESİ") {
                    in.putExtra("baslik", baslik);
                    b = "";
                }
                else if (((TextView) view).getText().toString() == "UMRENİN EDA ŞEKLİ") {
                    in.putExtra("baslik", baslik);
                    b = "";
                }
                else if (((TextView) view).getText().toString() == "UMREYE NİYET") {
                    in.putExtra("baslik", baslik);
                    b = "";
                }

                startActivity(in);
                return false;
            }
        });

        rehberler.setOnGroupExpandListener(new ExpandableListView.OnGroupExpandListener() {
            public void onGroupExpand(int groupPosition) {

                int len = new Islemler(rehber.this).getGroupCount();
                for (int i = 0; i < len; i++) {
                    if (i != groupPosition) {
                        rehberler.collapseGroup(i);
                    }
                }
            }
        });

    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {

        if (item.getItemId() == android.R.id.home) {
            Intent i = new Intent(getApplicationContext(), MainActivity.class);
            NavUtils.navigateUpTo(this, i);
            return true;
        }

        return super.onOptionsItemSelected(item);
    }
}
